### ISSUE TITLE
Simplifying Targets Causes Package Name Collision

### ISSUE THREAD

**Issue by mkilpatrick** [pubref/rules_protobuf#100]
We have a BUILD file (/src/foo):
```
load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

package(default_visibility = ["//visibility:public"])

java_proto_library(
    name = "protobuf",
    imports = ["src/"],
    proto_deps = ["//src/google/protobuf:protobuf"],
    protoc = "//tools:protoc",
    protos = glob(["**/*.proto"]),
)
```

That targets (/src/google/protobuf):
```
load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

package(default_visibility = ["//visibility:public"])

java_proto_library(
    name = "protobuf",
    imports = ["src/"],
    protoc = "//tools:protoc",
    protos = glob(["**/*.proto"]),
)
```

When we run buildifier, the target in the first BUILD file gets stripped to `["//src/google/protobuf"]`, which can't be found because //src/google/protobuf is the package name and clashes with the library name.

Our temporary solution is to name the library to something different so that it doesn't clash with the package name, which also prevents buildifier from stripping the target.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
