### ISSUE TITLE
Using a protobuf rule results in incorrect class file in deploy jar

### ISSUE THREAD

**Issue by robfig** [pubref/rules_protobuf#101]
I'm trying to compile a deploy jar using the Java Lightstep tracer, which uses gRPC. If the resulting artifact contains any protobufs compiled using 0.7.1 of this repository, the grpc AbstractManagedChannelImplBuilder.class file explicitly included as a dependency is silently replaced with some other version, leading to a MethodNotFoundError. 

Original issue opened:
https://github.com/lightstep/lightstep-tracer-java/issues/106

I've created a minimal reproduction of the issue:
https://drive.google.com/open?id=0B6pRdgZiBcCPUU5TODZiNS1MZnM

If you build a deploy jar, you will find that the class file does not match the one from grpc-core-1.4.0.jar.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
