### ISSUE TITLE
GRPC should probably be unpacked from a release, not downloaded from Git

### ISSUE THREAD

**Issue by variac** [pubref/rules_protobuf#102]
GRPC should probably be unpacked from a release archive, not downloaded from Git. To someone who understands how pieces fit together here, the switch shouldn't be that much work, so please consider implementing.

To quote [Bazel docs](https://bazel.build/versions/master/docs/be/workspace.html#git_repository): "Warning: this rule has several limitations. We recommend using http_archive instead for more robust and secure performance."

**Comment by pcj** [comment]
Grpc workspace loading has been re-done in #119 and should be *much* faster now.

**Comment by dmitry-xnor** [comment]
Epic change, updated my WORKSPACE reference and everything builds and runs fine.

Thanks a lot!
