### ISSUE TITLE
Failed to build caused by undefined reference when building boringssl dep

### ISSUE THREAD

**Issue by siyangy** [pubref/rules_protobuf#107]
Hi, our project uses rules_protobuf to build protobuf. Recently some of the users ran into the following build issue when building a dependency of rules_protobuf called boringssl:

Linking of rule '//modules/hmi/ros_node:ros_node_service' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-dbg/bin/modules/hmi/ros_node/ros_node_service '-Wl,-rpath,$ORIGIN/../../../_solib_k8/_U@ros_S_S_Cros_Ucommon___Uexternal_Sros_Slib' ... (remaining 8 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
**external/boringssl/boringssl-master-with-bazel/src/ssl/handshake_server.cc:778: error: undefined reference to 'tls13_server_handshake'**

Please see https://github.com/ApolloAuto/apollo/issues/166 for more information, thanks!

**Comment by siyangy** [comment]
Version: https://github.com/pubref/rules_protobuf/archive/v0.7.1.tar.gz

**Comment by pcj** [comment]
Closed by #110 

Thanks to @wanglei828 for pointing out the `chromium-stable-with-bazel` branch.  I'll cutting a new version 0.7.2 in the near future.
