### ISSUE TITLE
Support importpath on go_proto_library

### ISSUE THREAD

**Issue by mattmoor** [pubref/rules_protobuf#123]
I want to be able to use [this new kwarg](https://github.com/bazelbuild/rules_docker/blob/master/docker/testdata/BUILD#L510) to simplify [the importpath story](https://github.com/pubref/rules_protobuf/tree/master/go#import-paths) with `go_proto_library`.

In particular, I want to be able to check in a Go gRPC example ([see here](https://github.com/bazelbuild/rules_k8s/issues/11)) to `rules_k8s` without needing `//:go_prefix` defined, the solution to this is to use `importpath="..."` on `go_foo` targets (`go_image` exposes the signature of `go_binary` in my linked example).

I think the most logical solution would be to support an `importpath="..."` kwarg on `go_proto_library` that annotates the underlying `go_library` rule.

**Comment by mattmoor** [comment]
@ianthehat FYI

**Comment by mattmoor** [comment]
As background, the reason I don't want `//:go_prefix` is because it would mean dependents would need `rules_go` in order to consume `rules_k8s`, even though `rules_go` isn't needed outside of the examples.

**Comment by ianthehat** [comment]
In bazelbuild/rules_go#803 I added a new go_proto_library rule that fixes all the issues I know of with proto library rules for go, it already has this feature.
I am currently making minor adjustments to make sure we can also support building with the gogo proto generators (without changing any of the go_proto_library rules, it switches the underlying toolchain instead).

**Comment by mattmoor** [comment]
`rules_go` seems broken at `HEAD` (checksum mismatch):
```shell
$ bazel test ...
WARNING: /home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/io_bazel_rules_go/go/def.bzl:182:3: DEPRECATED: go_repositories has been deprecated. go_rules_dependencies installs dependencies the way nested workspaces should, and go_register_toolchains adds the toolchains
ERROR: /home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/org_pubref_rules_protobuf/protobuf/internal/require.bzl:46:13: no such package '@com_github_google_protobuf//': Error downloading [https://github.com/google/protobuf/archive/v3.4.0.tar.gz] to /home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/com_github_google_protobuf/v3.4.0.tar.gz: Checksum was f6600abeee3babfa18591961a0ff21e7db6a6d9ef82418a261ec4fee44ee6d44 but wanted cd55ee08e64a86cf12aaadd4672961813f592c194ed0c9ad94da0ec75acf219f and referenced by '//external:protobuf_clib'
ERROR: Analysis of target '//examples/hello-grpc/cc/client:client' failed; build aborted
INFO: Elapsed time: 3.246s
FAILED: Build did NOT complete successfully (37 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

I think this is the same thing that @ixdy and @dlorenc both independently got bitten by yesterday.

**Comment by mattmoor** [comment]
Once past the checksum failure, I'm still hitting:
```shell
$ bazel test ...
WARNING: /home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/io_bazel_rules_go/go/def.bzl:182:3: DEPRECATED: go_repositories has been deprecated. go_rules_dependencies installs dependencies the way nested workspaces should, and go_register_toolchains adds the toolchains
ERROR: /home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/com_github_golang_protobuf/proto/BUILD.bazel:3:1: in go_library rule @com_github_golang_protobuf//proto:go_default_library: 
Traceback (most recent call last):
        File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/com_github_golang_protobuf/proto/BUILD.bazel", line 3
                go_library(name = 'go_default_library')
        File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/io_bazel_rules_go/go/private/rules/library.bzl", line 32, in _go_library_impl
                ctx.toolchains["@io_bazel_rules_go//go:toolchain"]
key "@io_bazel_rules_go//go:toolchain" not found in dictionary
```

What is expected to define this toolchain?

**Comment by mattmoor** [comment]
If I do as directed by the deprecation notice I get something similar (maybe a race and both are a problem?):
```shell
$ bazel test ...
ERROR: /home/mattmoor/rules_k8s/examples/hello-grpc/proto/BUILD:28:1: in go_proto_library rule //examples/hello-grpc/proto:go: 
Traceback (most recent call last):
        File "/home/mattmoor/rules_k8s/examples/hello-grpc/proto/BUILD", line 28
                go_proto_library(name = 'go')
        File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/052ca0798388734beb518a18dbe118fe/external/io_bazel_rules_go/proto/def.bzl", line 16, in _go_proto_library_impl
                ctx.toolchains[ctx.attr._toolchain]
key "@io_bazel_rules_go//proto:go_proto" not found in dictionary
ERROR: Analysis of target '//examples/hello-grpc/go/server:server' failed; build aborted
INFO: Elapsed time: 9.581s
FAILED: Build did NOT complete successfully (64 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

**Comment by pcj** [comment]
Hi @mattmoor thanks for pointing out the `importpath` attribute in `go_library`.  You're welcome to try https://github.com/pubref/rules_protobuf/pull/124/commits/5b1ca3aae51cb1b5d9e79e4280ddc705407af136, or use the go_proto_library rule that @ianthehat and @pmbethe09 developed, whatever fits your use case best.

**Comment by mattmoor** [comment]
@pcj these work great, thanks.

**Comment by ianthehat** [comment]
For reference, you were probably missing the
```
load("@io_bazel_rules_go//proto:def.bzl", "proto_register_toolchains")
proto_register_toolchains()
```
which is unfortunately needed until the nested workspaces concept of Bazel arrives.
The error messages to do with toolchains in Bazel have been improved a lot since 0.5.4, the error you got there was very cryptic.
This is not actually documented yet, except by example. The documentation is going to undergo a major overhaul to catch up with all the new api's and features that have arrived recently in the coming weeks.
