### ISSUE TITLE
Go vendoring duplicate library artifacts (glog, etc)

### ISSUE THREAD

**Issue by bshi** [pubref/rules_protobuf#13]
This problem crops up for folks that vendor all of their go dependencies monorepo-style (Pattern 1 described in https://github.com/bazelbuild/rules_go/issues/16#issuecomment-216010843)

A strawman example: I use "govendor" and check in external dependencies directly into the "vendor" of my repository (Pattern 1).  I also have a utility similar to `gazelle` that generates BUILD files for go libraries that are buildable via "go get".

File `tools/artifact/proto/BUILD`
``` 
load("@org_pubref_rules_protobuf//bzl:go/rules.bzl", "go_proto_library")

go_proto_library(
    name = "go_default_library",
    visibility = ["//visibility:public"],
    protos = ["artifact.proto"],
    with_grpc = False,
)
```

The package for the protobuf DDL builds without issue.

Unfortunately, when I try to use the proto package as a dependency,

Content for `tools/artifact/db/BUILD`
``` 
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    visibility = ["//visibility:public"],
    srcs = ["store.go"],
    deps = [
        "//tools/artifact/proto:go_default_library",
        "//vendor/github.com/golang/glog:go_default_library",
        "//vendor/google.golang.org/cloud/datastore:go_default_library",
    ],
)

go_test(
    name = "go_tests",
    size = "small",
    srcs = ["store_test.go"],
    library = ":go_default_library",
    deps = [],
)
```

I get an error

```
ERROR: /???/tools/artifact/db/BUILD:17:1: error executing shell command: 'rm -rf bazel-out/local-fastbuild/bin/tools/artifact/db/go_tests.dir && mkdir -p bazel-out/local-fastbuild/bin/tools/artifact/db/go_tests.dir && mkdir -p bazel-out/local-fastbuild/bin/tools/artifact...' failed: linux-sandbox failed: error executing command /?????/.cache/bazel/_bazel_bshi/08ef9c7ff335ac2219f037954496dcb0/execroot/experiments.git/_bin/linux-sandbox ... (remaining 5 argument(s) skipped).
ln: failed to create symbolic link 'bazel-out/local-fastbuild/bin/tools/artifact/db/go_tests.dir/github.com/golang/glog.a': File exists
```

As far as I can tell, this is because rules_protobuf is pulling in glog as a dependency as an external git repository and then pointing to custom BUILD rules.  Those build rules in turn are colliding with my declaration of `"//vendor/github.com/golang/glog:go_default_library",`  There currently isn't a way short of forking this repo to adapt the dependencies and target names that are hard coded: https://github.com/pubref/rules_protobuf/blob/master/bzl/go/class.bzl#L118

I don't have a good general solution to prescribe here but wanted to call out the issue.

**Comment by pcj** [comment]
I'll think about it a bit more, but off the top of my head, would this work?

1. Change the hardcoded entries in go/class.bzl compile_deps to an "//external:glog" form.
2. Support suppression of loading of unwanted deps, such as:

```python
protobuf_repositories(
    exclude = ["com_github_golang_glog"]
)

bind(
   name = "glog", 
   actual = "//vendor/github.com/golang/glog"
)
```

Can you also try changing your dependency from the library to the source? (note the ".pb" implicit dependecy)?  Curious if that is a workaround

```python
go_library(
    name = "go_default_library",
    visibility = ["//visibility:public"],
    srcs = [
        "store.go",
        "//tools/artifact/proto:go_default_library.pb",
    ],
    deps = [
        "//vendor/github.com/golang/glog:go_default_library",
        "//vendor/google.golang.org/cloud/datastore:go_default_library",
    ],
)
```

**Comment by bshi** [comment]
Using `bind` was my thought as well and works for me.  I will try the report back regarding the implicit `.pb` dependency tonight.  Thanks Paul.

**Comment by pcj** [comment]
Did the bind solution work without forking?

**Comment by bshi** [comment]
The workaround resulted in

```
ERROR: /???/experiments.git/tools/artifact/db/BUILD:7:1: error executing shell command: 'rm -rf bazel-out/local-fastbuild/bin/tools/artifact/db/go_default_library.a.dir && mkdir -p bazel-out/local-fastbuild/bin/tools/artifact/db/go_default_library.a.dir && mkdir -p bazel-out/local-fast...' failed: linux-sandbox failed: error executing command /???/.cache/bazel/_bazel_bshi/08ef9c7ff335ac2219f037954496dcb0/execroot/experiments.git/_bin/linux-sandbox ... (remaining 5 argument(s) skipped).
???/experiments.git/tools/artifact/db/store.go:11: can't find import: "???/experiments.git/tools/artifact/proto"
```

Have not had a chance to investigate further.  I haven't attempted the bind approach myself (no ETA unfortunately).
