### ISSUE TITLE
*_proto_library deps do not work

### ISSUE THREAD

**Issue by kgreenek** [pubref/rules_protobuf#130]
I have two libraries (library "a" and "b"). Library a depends on b. My BUILD file looks like this:

```python
py_proto_library(
    name = "a_py_proto",
    protos = ["a.proto"],
    deps = [":b_py_proto"],
)

py_proto_library(
    name = "b_py_proto",
    protos = ["b.proto"],
)
```

When building a, I get errors to the effect of: 
```
b.proto: File not found.
a.proto: Import "b.proto" was not found or had errors.
```

Are deps supported in the py_proto_library rule?

**Comment by kgreenek** [comment]
As a workaround, I am adding the b proto files as "inputs", like this:

```python
py_proto_library(
    name = "a_py_proto",
    inputs = [":b_proto_files"],
    protos = ["a.proto"],
)

filegroup(
    name = "b_proto_files",
    srcs = ["b.proto"],
)

py_proto_library(
    name = "b_py_proto",
    protos = [":b_proto_files"],
)
```

This is a hack, but it works temporarily, and I can build all the targets I need. The obvious drawback is that if b depends on another library "c", then I also have to add c_proto_files to a's inputs.

**Comment by pcj** [comment]
Thanks will investigate

**Comment by kgreenek** [comment]
I also observed that this affects the cc_proto_library rule as well. So it's not specific to py_proto_library.

**Comment by michaelsafyan** [comment]
Any updates? I'm encountering this issue, as well.

**Comment by kgreenek** [comment]
Any updates on this? As you can imagine, after a year or so of using the workaround I described in my above post, we're experiencing considerable pain as our codebase continues to grow (due to the fact that there is no way to propagate transitive py_proto dependencies).

**Comment by raliste** [comment]
Updates?

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
