### ISSUE TITLE
Provide a way to use locally installed protoc and grpc

### ISSUE THREAD

**Issue by sumit-g** [pubref/rules_protobuf#137]
Today this extension requires that grpc and protoc is downloaded and compiled. We develop inside a container where we have preinstalled the necessary dependencies. It will be great if we can skip the unnecessary download and compile.

I understand that this is only done once but in a team, everyone's workspace is doing that. Also every time something changes on our test servers and they are reset, the process of downloading protoc/grpc starts again.

**Comment by sumit-g** [comment]
Thanks for the tip. I will try that.

**Comment by sumit-g** [comment]
Actually just realized that this wont work as in our case the workspace is not part of the container.

**Comment by pcj** [comment]
I'll have to think about it.  Another workaround to consider would be use something like https://github.com/buchgr/bazel-remote.  This does not solve the problem but may make it more tolerable.  Workspaces would still be compiling everything from scratch though.  

FYI if you have not upgraded to https://github.com/pubref/rules_protobuf/releases/tag/v0.8.0 that might help too.

cc: @buchgr

**Comment by sumit-g** [comment]
I received another request from a fellow engineer today which I believe is on similar lines. He wanted to not use boringssl but instead, use locally available SSL library. I don't know if that's possible. But will be good to be able to override defaults.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
