### ISSUE TITLE
Protobuf import errors with multiple external projects

### ISSUE THREAD

**Issue by kgreenek** [pubref/rules_protobuf#139]
I am seeing an issue on HEAD (as of 10/4) where python binaries fail to run when the project depends on multiple external proto libraries.

Here is an example repo I set up to illustrate the issue:
https://github.com/kgreenek/bazel_timestamp_server

It's a simple grpc timestamp server that returns a google.protobuf.Timestamp object with the current time.

It depends on both the Google well-known protos, and googleapis (https://github.com/googleapis/googleapis).

When you build the repo, and try to run the server or the client, the following errors are printed:
```bash
Traceback (most recent call last):
  File "/home/kevin/Projects/bazel_protobuf_issue/bazel-bin/client.runfiles/__main__/client.py", line 4, in <module>
    import timestamp_service_pb2
  File "/home/kevin/Projects/bazel_protobuf_issue/bazel-bin/client.runfiles/__main__/timestamp_service_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named 'google.protobuf'
```

It's definitely possible that there is just something wrong with how I am importing the libraries; in which case I would greatly appreciate any advice on the correct way I should be importing these. 

If you remove all references to googleapis in the proto and BUILD file, it builds and runs as expected.

Thanks!

**Comment by kgreenek** [comment]
NOTE: In order to import googleapis at all, you'll need a version of rules_protobuf with this commit:
https://github.com/pubref/rules_protobuf/commit/ff3b7e7963daa7cb3b42f8936bc11eda4b960926

**Comment by pcj** [comment]
I don't think I'll have time to look at this much more today but I did make some progress using rules_python:

```python
# BUILD
load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_library")
load("@pip_requirements//:requirements.bzl", "requirement")

py_binary(
    name = "client",
    srcs = ["client.py"],
    deps = [":py_proto"],
)

py_binary(
    name = "server",
    srcs = ["server.py"],
    deps = [
        ":py_proto",
        requirement("asyncio"),
    ],
)

filegroup(
    name = "protos",
    srcs = glob(["*.proto"]),
    visibility = ["//visibility:public"],
)

# NOTE: The *_proto_library rules do not correctly handle deps, so we have to add all dependent
# proto files as inputs. See: https://github.com/pubref/rules_protobuf/issues/130
PROTO_IMPORTS = [
    "external/com_google_protobuf/src/",
    "external/googleapis_archive",
]
PROTO_INPUTS = [
    "@com_google_protobuf//:well_known_protos",
    "//external:googleapis_protos",
]

py_proto_library(
    name = "py_proto",
    imports = PROTO_IMPORTS,
    inputs = PROTO_INPUTS,
    protos = [":protos"],
    visibility = ["//visibility:public"],
    deps = ["//external:googleapis_py_proto"],
)
```

```python
# WORKSPACE

http_archive(
    name = "io_bazel_rules_python",
    sha256 = "4ed20f825f56ef37b110c827491194ba52d783d2c1a15a23100aff7ef839631a",
    strip_prefix = "rules_python-44fdf5f24a4b634ef7b0f86e7a017f4d8d5aa899",
    urls = ["https://github.com/bazelbuild/rules_python/archive/44fdf5f24a4b634ef7b0f86e7a017f4d8d5aa899.zip"],
)

load("@io_bazel_rules_python//python:pip.bzl", "pip_repositories", "pip_import")

pip_repositories()

pip_import(
   name = "pip_requirements",
   requirements = "//:requirements.txt",
)

load("@pip_requirements//:requirements.bzl", "pip_install")

pip_install()

local_repository(
    name = "org_pubref_rules_protobuf",
    path = "../..",
)

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_repositories")

py_proto_repositories()

new_http_archive(
    name = "googleapis_archive",
    build_file = "//third_party:googleapis.BUILD",
    sha256 = "df585427959ebb9949ca12a45888b50a5b8edcb2b270aea1800225d159a49ff6",
    strip_prefix = "googleapis-3273178ea4684acc4f512f7bef7349dd72db88f6",
    urls = ["https://github.com/googleapis/googleapis/archive/3273178ea4684acc4f512f7bef7349dd72db88f6.tar.gz"],
)

bind(
    name = "googleapis_protos",
    actual = "@googleapis_archive//:protos",
)

bind(
    name = "googleapis_py_proto",
    actual = "@googleapis_archive//:py_proto",
)
```

**Comment by kgreenek** [comment]
This is really close! Thanks for the pip_import() pointer, I wasn't aware of that feature. I also had to add requirement("grpcio") to the server and client deps.

I ran into problems trying to import asyncio. Possibly python-version related? When I built and then ran the server or client I saw:
```bash
Traceback (most recent call last):
  File "/home/kevin/Projects/bazel_timestamp_server/bazel-bin/server.runfiles/__main__/server.py", line 2, in <module>
    import asyncio
  File "/home/kevin/Projects/bazel_timestamp_server/bazel-bin/server.runfiles/pypi__asyncio_3_4_3/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/home/kevin/Projects/bazel_timestamp_server/bazel-bin/server.runfiles/pypi__asyncio_3_4_3/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

Anyways, I removed the references to asyncio, and everything works! I pushed the changes up to my repo. Another improvement by using the pip_import() rule is that I no longer have to create a virtualenv!

Unfortunately, I have to figure out the asyncio issues to use this in my real project, but that's unrelated to this issue.

**Comment by pcj** [comment]
I had issues with asyncio via `rules_python` as well. I see you created https://github.com/bazelbuild/rules_python/issues/23 so that's good.

**Comment by kgreenek** [comment]
I did end up finding a work-around in that bug to get projects with asyncio to work, but you can't use "bazel run".

I also had to do this to get it to fully work: https://github.com/bazelbuild/rules_python/pull/22

You're probably good to close this issue. It must have been that bazel didn't know about the pip dependencies. Using the new pip_import() rule appears to have solved it!

**Comment by pcj** [comment]
SGTM
