### ISSUE TITLE
Integrate .runfiles directory for proto_language's pb_plugin

### ISSUE THREAD

**Issue by timblakely** [pubref/rules_protobuf#141]
I'm trying to get [`ts-protoc-gen`](https://github.com/improbable-eng/ts-protoc-gen/) up and running with rules_protobuf. I'm close, but hitting an issue with `proto_language`'s `pb_plugin` the protoc skylark action. `ts-protoc-gen` is written in nodejs, so I'm leveraging [bazelbuild/rules_nodejs](https://github.com/bazelbuild/rules_nodejs) to build a `nodejs_binary`. The "executable" that's generated isn't statically linked but rather a wrapper script that finds the `<target>.runfiles` directory containing the node implementation, js files, and supporting node_modules libraries. 

Unfortunately `proto_language`'s struct defines `pb_plugin = ctx.executable.pb_plugin`. Bazel gathers up all the target's executable outputs from the target when generating `ctx.executable.<target>`, but does *not* include the runfiles directory. This leads to the protoc's action adding the wrapper script to the action's inputs but not the required runfiles directory, causing the plugin to fail to run. This appears to affect pb_plugins that are written in both node and python (unless you wrap it in a [.par](https://github.com/google/subpar))

I think it might be possible to use [`ctx.resolve_command`](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#resolve_command)'s input_manifests to include the runfiles directory for the executable in addition to the actual executable itself.

**Comment by pcj** [comment]
Yes I see what you mean.  If the nodejs_binary returned a files provider in addition to a runfiles provider, you might just be able to reference that to the pb_inputs attribute.  

Once could experiment [around here](https://github.com/pubref/rules_protobuf/blob/master/protobuf/internal/proto_language.bzl#L7 to see if the ctx.resolve_command could be used to extract those dependencies from the pb_plugin and augment the inputs with those files.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
