### ISSUE TITLE
Compilation fails if BUILD file is in workspace root and proto is in some other directory

### ISSUE THREAD

**Issue by sumit-g** [pubref/rules_protobuf#142]
Here is how to reproduce.
1) In the workspace root directory, create a directory tree say a/b/c
 ` mkdir -p a/b/c`

2) copy a simple proto file called test.proto to the 'c' directory.

3) Now try to compile it from workspace root using the following BUILD file in workspace root.

```
package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
   name = "test_proto",
   protos = [
       "a/b/c/test.proto",
   ],
)
```
4) Notice how it fails
```
ubuntu@ubuntu-xenial:/vagrant/bazel$ bazel build :all
INFO: Found 2 targets...
ERROR: /vagrant/bazel/BUILD:5:1: output 'b/c/test.pb.h' was not created.
ERROR: /vagrant/bazel/BUILD:5:1: output 'b/c/test.pb.cc' was not created.
ERROR: /vagrant/bazel/BUILD:5:1: output 'b/c/test.grpc.pb.h' was not created.
ERROR: /vagrant/bazel/BUILD:5:1: output 'b/c/test.grpc.pb.cc' was not created.
ERROR: /vagrant/bazel/BUILD:5:1: not all outputs were created or valid.
INFO: Elapsed time: 0.432s, Critical Path: 0.06s
```

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
