### ISSUE TITLE
Python compile fails if the src file path has a dot in a directory name

### ISSUE THREAD

**Issue by sumit-g** [pubref/rules_protobuf#143]
if one of the source files is in a subdirectory and the subdirectory name has a dot in it, py_proto_compile fails.

For us this is happening because one of the subdirs is github.com (importing a gogo proto).

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
