### ISSUE TITLE
java_proto_library fails on generated proto file

### ISSUE THREAD

**Issue by tomgr** [pubref/rules_protobuf#144]
If the protos for a java_proto_library are generated, then the .jar file is not generated. For example, adding the following in `tests/generated_proto_file/BUILD` reproduces the failure:
```
java_proto_library(
   name = "java_default_library",
   protos = ["simple.proto"],
)

java_proto_library(
   name = "java_copy_library",
   protos = ["copy.proto"],   
   with_grpc = True,
)
```

The above gives the following output:
```
ERROR: /Users/Tom/src/rules_protobuf/tests/generated_proto_file/BUILD:42:1: output 'tests/generated_proto_file/java_copy_library.pb_java.jar' was not created.
```

Looking at the invocation of protoc:
```
bazel-out/host/bin/external/com_google_protobuf/protoc
  --descriptor_set_out=bazel-out/darwin_x86_64-fastbuild/genfiles/tests/generated_proto_file/java_copy_library.pb.descriptor_set
  --java_out=.
  --plugin=protoc-gen-grpc-java=bazel-out/host/genfiles/java/protoc_gen_grpc_java
  --grpc-java_out=.
  --proto_path=.
  bazel-out/darwin_x86_64-fastbuild/genfiles/tests/generated_proto_file/copy.proto
```
The issue appears to be ``--java_out=.``: protoc will recognise this as a directory and thus outputs the .java files individually, rather than creating a single .jar file.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
