### ISSUE TITLE
Support propagation of dependencies with objc_proto_library

### ISSUE THREAD

**Issue by spinorx** [pubref/rules_protobuf#146]
Currently if objc proto lib X depends on objc photo library Y,  building X gives error saying can't find Y's generated headers.

**Comment by pcj** [comment]
Can you provide a simple repro case?

**Comment by spinorx** [comment]
Here is pull request with the test  https://github.com/pubref/rules_protobuf/pull/147

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
