### ISSUE TITLE
Blockers to building Scala protobufs

### ISSUE THREAD

**Issue by promiseofcake** [pubref/rules_protobuf#149]
Thanks for all of your work on this @pcj, just wondering if you can think of any blockers for compiling scala protobufs as either an additional module, or as an alternate output from the java rules.

bazelbuild/rules_scala provides us this rule: [scalapb_proto_library](https://github.com/bazelbuild/rules_scala#scalapb_proto_library) which we can pass either a native `java_proto_library` or `proto_library` target to in order to build Scala outputs.

The problem we are running into is that we cannot use this repo's `java_proto_library` rule because it returns a `java_library` as opposed to a `java_proto_library`

`ERROR: /path/to/BUILD:13:1: in deps attribute of scalapb_proto_srcjar rule //sample/src/main/scala/com/path/to:scala_protos_events_srcjar: java_library rule '//protobufs:java_target' is misplaced here (expected proto_library or java_proto_library). Since this rule was created by the macro 'scalapb_proto_library', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_lucas/a550f2fe526d3619d45a5ababf8e0f83/external/io_bazel_rules_scala/scala_proto/scala_proto.bzl:468:16`
`ERROR: Analysis of target '//sample/src/main/scala/com/path/to:scala_protos_events_srcjar' failed; build aborted`

Thanks.

**Comment by pcj** [comment]
To better understand your requirements...  What is not present in the native `java_proto_library` in conjunction with `scalapb_proto_library` that you want to use this repo for? (Not that I'm trying to discourage you :) )

**Comment by promiseofcake** [comment]
The main reason is that we are so bought-in to rules_protobuf for all of our protobuf generation (Go, C++, Node, Java) it would be simplest to continue down that road where all the dependencies are provided through the `repository` rules. 

I think I am going to upgrade our rules (we are on `0.7.1`) so we can get the renamed dependencies (which is what Bazel is looking for) and see if we can use the native rules.

I think though I can use this: https://github.com/bazelbuild/rules_scala/pull/322 and then still use the current pubref rules 😄 , will keep you posted.

**Comment by pcj** [comment]
Got it.  It would also be possible to write a scala_proto_library rule here without too much fuss, but if  bazelbuild/rules_scala#322 satisfies it, that sounds like a good option.

**Comment by promiseofcake** [comment]
I have dug deep into this issue and figured some things out. The problem I am trying to solve is that my `.proto` files are owned by another workspace which only exposes the pubref `java_proto_library` targets at present.

My thought was if I could use those targets as inputs to the `scalapb_proto_library` targets I would be able to maintain that separation. However, it seems that one needs to pass both the `java_library` output from the pubref rules and either a `proto_library` or a native `java_proto_library` to the compiler in order for it to work.

The workspace which owns my protos is stuck on older version of Bazel (and related dependencies) so that is where the complication arises. I think for now we are just going to rely on Java protos until we can schedule time to get our proto repo updated.

Thanks for your input 👍 .

**Comment by promiseofcake** [comment]
Closing in favor of following developments in [bazelbuild/rules_scala](https://github.com/bazelbuild/rules_scala#scalapb_proto_library)
