### ISSUE TITLE
rules_protobuf can generate grpc_gateway files but not grpc_gateway_swagger definitions

### ISSUE THREAD

**Issue by achew22** [pubref/rules_protobuf#15]
This would be nice to have

**Comment by pcj** [comment]
Should not be too hard to add.

**Comment by pcj** [comment]
Implemented in 84f5b460e6512eddcc0f33e8d8c3069aec04fab4, on master.  Can you confirm and close issue?

**Comment by achew22** [comment]
@pcj Thanks so much for taking this on, it's looking really good! Quick question and I think this might be a misunderstanding on my part.

When I run `blaze build //examples/helloworld/grpc_gateway:swagger` (your newly created target I get the following output:

```
INFO: Found 1 target...
Target //examples/helloworld/grpc_gateway:swagger up-to-date:
  bazel-bin/examples/helloworld/grpc_gateway/helloworld.swagger.json
INFO: Elapsed time: 0.166s, Critical Path: 0.00s
```

This output makes me think that there should be a target `//examples/helloworld/grpc_gateway:helloworld.swagger.json` that I can depend on in another rule. A genrule for example. However when I build `//examples/helloworld/grpc_gateway:helloworld.swagger.json` I get the classic error message:

```
ERROR: no such target '//examples/helloworld/grpc_gateway:helloworld.swagger.json': target 'helloworld.swagger.json' not declared in package 'examples/helloworld/grpc_gateway' defined by /Users/achew22/Projects/rules_protobuf/examples/helloworld/grpc_gateway/BUILD.
```

Am I doing something weird here? It seems like that file target should exist

**Comment by pcj** [comment]
You should be able to depend on the `:swagger` target directly in your genrule.  This is true of all members of the *_proto_compile family, of which `grpc_gateway_swagger_compile` belongs.

All `*_proto_library` rules are actually a composition of a proto_compile rule + a library rule.  So a `go_proto_library` rule named `foo` first emits a proto_compile of the form `foo.pb` and then depends on the output of that for a `go_library` rule.  So if you want the compiled `foo.a` output, depend on `:foo`.  If you want the generated files, depend on the implicit target `foo.pb`, which yields the `*.pb.go` files.

Hopefully that was not too longwinded.  Curious what your genrule does... What are you feeding it into?

**Comment by achew22** [comment]
In the case of a swagger output there isn't a library to be consumed so that seems reasonable. My genrule, as I suspect you know, generates a swagger client library using this as the input. It seems to be working. Thanks so much for doing this. I'll look into open sourcing it. Unfortunately my ambitions are incompatible with my time constraints :wink:.

Thank you so much for implementing this, it is hugely appreciated.
