### ISSUE TITLE
py_proto_library does not support proto files that have '-' in the filename

### ISSUE THREAD

**Issue by lingyunruansc** [pubref/rules_protobuf#157]
Hi,

Looks like currently the py_proto_library does not support proto files that have `"-"` in the filename. We know it's not ideal to have a proto file with names like `foo-bar.proto`, but we do have some cases due to legacy code.

When generating python code, `protoc` will compile the `foo-bar.proto` into `foo_bar_pb2.py` automatically (as documented in [1]). But in this case, the `proto_compile` rule expected output to be `foo-bar_pb2.py` because of logic in [2].

It would be good for python if we can do `replace('-', '_')` for expected outputs of proto compilation.

Thanks,
Lingyun

[1] https://developers.google.com/protocol-buffers/docs/reference/python-generated
[2] https://github.com/pubref/rules_protobuf/blob/v0.8.1/protobuf/internal/proto_compile.bzl#L194-L196

**Comment by pcj** [comment]
Thanks @lingyunruansc this is useful info.  We should do that.

**Comment by mattmoor** [comment]
FWIW, these are treated equivalently in the world of PIP package names and we basically have this exact `replace` in `rules_python` :)

**Comment by moooyu** [comment]
Hi, is there any update on this? We encountered exactly the same issue too :(  Thanks!

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
