### ISSUE TITLE
Protobuf rules should collect *.proto files and preprocess import lines.

### ISSUE THREAD

**Issue by michaelsafyan** [pubref/rules_protobuf#158]
Minimal steps to reproduce:

1. Create three repositories:
    - common_types_repo for shared \*.proto files used by multiple projects
    - apispec_repo for an API that uses types from common_types_repo
    - apiserver_repo for the implementation of said API server

2. Define multiple `*.proto files in common_types_repo. Create proto_libarry, py_proto_library, and java_proto_library rules for these protos. Have some protos "import" other protos here.

3. Define a \*.proto file in apispec_repo that defines a gRPC service. Have it use the types in the common_types_repo in the request/response protos. Include the common_types_repo using the `git_repository` WORKSPACE rule (rather than through git submodules or some other mechanism). Define, as before, proto_library, py_proto_library, and java_proto_library rules for this service.

4. Create a `main.py` file in apiserver_repo that implements the gRPC service from apispec_repo. Have the gRPC service depend on the protos generated from common_types_repo and apispec_repo. Include both common_types_repo and apispec_repo through the `git_repository` WORKSPACE rule.

Observed:

It is literally impossible to do this in a way that works. Additionally, the process involves redundant compilation between the proto_library, py_proto_library, and java_proto_library rules. It also involves redudnantly creating a "filegroup" to gather the *.proto files and reference them from the "inputs" rule and requires specifying a "imports" stanza that is similarly redundant with "deps". It is possible to successfully get through a valid apispec_repo (only in an ugly way, though), but there is no way to get the apiserver_repo to build successfully (at least not without hours and hours of head scratching).

Expected:

This use case should be relatively easy to support. In particular, I expect that it should look like:

```
#common_types_repo
proto_library(
    name = "common_types_proto",
    srcs = [glob("*.proto")],
)

py_proto_library(
    name = "common_types_python",
    deps = [":common_types_proto"],
)

py_proto_library(
    name = "common_types_java",
    deps = [":common_typs_proto"],
)
```
```
# apispec_repo
proto_library(
   name = "api_proto",
   srcs = [glob("*.proto")],
   deps = [
      "@common_types_repo//:common_types_proto",
   ],
)

py_proto_library(
   name = "api_python",
   deps = [
      ":api_proto",
      "@common_types_repo//:common_types_proto",
   ],
)

java_proto_library(
   name = "api_java",
   deps = [
     ":api_proto",
      "@common_types_repo//:common_types_proto",
   ],
)

```

```
#apiserver_repo

py_binary(
   name = "apiserver",
   srcs = ["main.py"],
   deps = [
      "@apispec_repo//:api_python",
      "@common_types_repo//:common_types_python",
   ],
)
```        

To make it as easy as above, all these rules should preprocess *.proto files and any dependencies that refer to protos to automatically rewrite "import" lines. This rewriting should make it possible to refer to imports using bazel target syntax (e.g. "@myexternalrepo//path/to/the/file.proto") and should automatically add the correct dependencies to "inputs" and "imports" based on "deps".

It would also help to reduce the amount of work being performed here if the rules accepted specifying a proto_library rule in "deps" in lieue of supplying values in "protos" to avoid duplicative compilation.

**Comment by pcj** [comment]
Curious: are you guys are doing proto import pre-processing and rewriting with blaze internally?  Agree it could solve some headaches, but not trivial to implement (or maybe it is, if I thought about it more...)

**Comment by pcj** [comment]
Also, are you suggesting something like:

```proto
syntax "proto3"

import "@googleapis//:google/api/http.proto";

message Foo {
   ...
}
```

That's an interesting idea, but it would require an action node in the execution graph to (1) read the file (2) parse the import statement, (3) augment the execution graph based on the results of (2).  I don't think that's currently possible with bazel.  Perhaps it would be possible with an aspect.

**Comment by michaelsafyan** [comment]
Yes, that is what I am suggesting. I am also suggesting implicitly adding
the "@repo//" qualifier to the unqualified imports from a *.proto file when
that proto is listed as a dep using a label with the "@repo//" prefix so
that it can find imports from the same repo without that foreign repo
having to use the "@repo//" qualifier on imports of local *.proto filles
within that repo.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
