### ISSUE TITLE
Any way to use go_proto_library and gogo_proto_library?

### ISSUE THREAD

**Issue by junghoahnsc** [pubref/rules_protobuf#165]
Hello,

I'm trying to migrate to use gogoproto since goprotobuf is too slow.
Since I can't change the whole code at one go, I want to have both during migration.
But gogoproto and goprotobuf rules generate the same go file from the proto, so I can't use them at the same time. Is there any way to have both rules at the same time?

Thanks,

**Comment by pcj** [comment]
Off the top of my head, not unless the build rule names are different.  You might look into buildozer to automate the renaming/commenting out of various build rules.

https://github.com/bazelbuild/buildtools/tree/master/buildozer#do-multiple-changes-at-once

**Comment by junghoahnsc** [comment]
Thanks for the suggestion. 
I tried different names like xxx_proto_go and xxx_proto_gogo, but the issue was the generated Go file was same like xxx.pb.go. For now, I'm trying to migrating to gogo proto in one go :)

**Comment by pcj** [comment]
Thanks, hopefully your migration will not be too painful :smiling_imp: .  Note there is #166 coming as a fix for gogo with bazel 0.8.0.

**Comment by junghoahnsc** [comment]
Cool! Thanks for the info!

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
