### ISSUE TITLE
Support for native bazel proto_library

### ISSUE THREAD

**Issue by kyessenov** [pubref/rules_protobuf#168]
Are there plans to use native proto_library rules?
Ref: https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library

**Comment by pcj** [comment]
Short answer is yes.  `proto_library` was rather crippled when this repo first got started, but certainly it should be re-written to accept / interact with the `proto` provider.  I have not had the chance to explore how difficult that would be as of yet, but I suspect it may not be terribly difficult (probably will regret premature optimism there...)

**Comment by kyessenov** [comment]
That's great to hear! [Envoy APIs](https://github.com/envoyproxy/data-plane-api) use macros around native proto_library to generate C++ and python code, and I'm interested in adding gogo to that list.

**Comment by raliste** [comment]
Any updates? Particularly to reuse a set of proto sources into different pubref proto rules.

**Comment by pcj** [comment]
Note: these rules have been re-written FOR THIS VERY ISSUE and migrated to https://github.com/stackb/rules_proto. 

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
