### ISSUE TITLE
Cant use examples outside of the rule_protobuf repo

### ISSUE THREAD

**Issue by davejohnston** [pubref/rules_protobuf#171]
Hi, I was trying to build upon the golang grpc-gateway examples under
rules_protobuf/examples/helloworld/grpc_gateway

I tried extracting this into my own project, but I get errors when trying to build.  Some of this was initially because rules like:
 load(
       "//grpc_gateway:rules.bzl",
       "grpc_gateway_proto_compile",
       "grpc_gateway_proto_library",
       "grpc_gateway_swagger_compile",
       "grpc_gateway_binary",
      "GRPC_GATEWAY_DEPS",
  )

were loading rules.bzl locally.  I tried changing that to load("@org_pubref_rules_protobuf//grpc_gateway:rules.bzl")

This gets me a bit further, but I'm still seeing errors like: 

```
bazel build //proto:test
ERROR: .../go/src/github.com/testrepo/bazel_test/proto/BUILD:7:1: no such package '@com_github_grpc_ecosystem_grpc_gateway//utilities': BUILD file not found on package path and referenced by '//proto:test'
```

I can't see where the packge ''@com_github_grpc_ecosystem_grpc_gateway//utilities':' is loaded in the examples.
Is there any guidelines on how to get these examples working outside of the rules_protobuf repo?

**Comment by pcj** [comment]
Yeah it looks like the grpc_gateway code needed a little TLC.  I pushed #172 as an updated integration test.  Will wait to merge until travis passes.

**Comment by davejohnston** [comment]
Thanks - I pulled and tried this out locally.  I can now generate the gateway code.  I did have one problem though when I try a rule that uses multiple protos i.e.

if I create a 
helper.proto that defines HelperList and use that in greeter.proto

Then if I update the rule to look like this:

```
grpc_gateway_proto_library(
    name = "greeter_grpc_gateway_go_proto",
    protos = [
    ┆   "helper.proto",
    ┆   "greeter.proto",
    ],
    importpath = "github.com/pubref/rules_protobuf/greeter",
    deps = [
    ┆   "//proto:go_provider_library",
    ],
    visibility = [
    ┆   "//visibility:public",
    ],
)
```

Then the error is:

```
ERROR: /.../example/grpc_gateway/proto/BUILD:10:1: output 'proto/helper.pb.gw.go' was not created
ERROR: /.../example/grpc_gateway/proto/BUILD:10:1: not all outputs were created or valid
```

This makes sense in that I don't expect helper.pb.gw.go to be generated, but it's not clear how I create  a gateway, when I have multiple proto files?

**Comment by davejohnston** [comment]
@pcj Your PR solved my initial problem.  I hit another separate issue, which I raised in #173, but I think you can close this once you merge.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
