### ISSUE TITLE
grpc_gateway_proto_library Import can't find local proto files

### ISSUE THREAD

**Issue by davejohnston** [pubref/rules_protobuf#173]
Hi,
Using grpc_gateway_proto_library I can build a simple  grpc gateway.  But when I work on a more complex example, where there are multiple source protos I get errors.  It maybe related to #64  i.e.

With a sample project I have the following 2 protos

proto/message.proto // Defines the hello request/reply messages
proto/greeter.proto // Defines a service that uses the request/reply messages.

And a build file like this:

```
load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_library")
load("@org_pubref_rules_protobuf//grpc_gateway:rules.bzl", "grpc_gateway_proto_library", "grpc_gateway_swagger_compile")

go_proto_library(
    name = "messages",
    imports = [
        "external/com_github_google_protobuf/src/",
    ],
    inputs = [
        "@com_github_google_protobuf//:well_known_protos",
    ],
    protos = [
        "message.proto",
    ],
    importpath = "github.com/pubref/rules_protobuf/greeter",
    deps = [
        "@com_github_golang_protobuf//ptypes/any:go_default_library",
    ],
    verbose = 0,
)

grpc_gateway_proto_library(
    name = "greeter_grpc_gateway_go_proto",
    protos = [
        "greeter.proto",
    ],
    importpath = "github.com/pubref/rules_protobuf/greeter",
    deps = [
        ":messages"
    ],
    visibility = [
        "//visibility:public",
    ],
)

grpc_gateway_swagger_compile(
    name = "greeter_swagger",
    protos = [
        "greeter.proto",
    ],
)
```

When trying to run the build I get the following:

```
    proto/message.proto: File not found.
    greeter.proto: Import "proto/message.proto" was not found or had errors.
```

Techncially I could merge these two proto files and that would solve the problem, but the real project has 5-6 protos that define messages, and multiple services that share messages, so it makes sense to keep them in separate files.

I've pushed the example to my fork here:
https://github.com/davejohnston/rules_protobuf/tree/grpc-gateway-update-multi-protos

**Comment by davejohnston** [comment]
After some futher debug.
If I run with verbose output I see the command that is executed:

```
cd /private/var/tmp/_bazel_dave.johnston/964395dbdca0f7afcfa7ec8c6f178015/execroot/__main__ && \
  exec env - \
  /bin/bash -c 'bazel-out/host/bin/external/com_google_protobuf/protoc --descriptor_set_out=bazel-out/darwin-fastbuild/genfiles/proto/greeter_grpc_gateway_go_proto.gw.descriptor_set --plugin=protoc-gen-grpc-gateway=bazel-out/host/bin/external/com_github_grpc_ecosystem_grpc_gateway/protoc-gen-grpc-gateway/darwin_amd64_stripped/protoc-gen-grpc-gateway --grpc-gateway_out=Mgoogle/api/annotations.proto=google.golang.org/genproto/googleapis/api/annotations:bazel-out/darwin-fastbuild/genfiles --proto_path=. --proto_path=external/com_google_protobuf/src/ --proto_path=external/com_github_grpc_ecosystem_grpc_gateway_googleapis/ proto/greeter.proto'
```

If I manually run this, it succeeds, but executing via the bazel build command it fails each time.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
