### ISSUE TITLE
Not possible to use protos that `import` generated protos

### ISSUE THREAD

**Issue by jondo2010** [pubref/rules_protobuf#174]
A proto library I'm using has a `version.proto` that gets generated from `version.proto.in` by replacing placeholders with a version triplet. I'm using a `genrule` to create this, and Bazel places this in `genfiles`.

Maybe I'm missing something, but it doesn't seem possible to pass the path to this generated file to `--proto_path`, which is needed since the rest of the library does `import "version.proto"`

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
