### ISSUE TITLE
Python protobuf dep

### ISSUE THREAD

**Issue by smr277** [pubref/rules_protobuf#18]
Using `py_binary` or `py_library` with a dependency of a `py_proto_compile` build doesn't work with the error ` does not have mandatory provider 'py'`.
Forked the repo and working on it - but I really have no idea what's wrong atm :P.

**Comment by pcj** [comment]
Are you putting the `py_proto_compile` label in the `srcs` or `deps` attribute of `py_library`?  Try putting it in `srcs`.  

However, getting the protobuf py (or grpc) dependencies is not something I've tackled yet. I'm thinking it needs a workspace rule like `pip_library` or `pypi_library` that downloads and installed deps better.

Interested to see how it goes...

**Comment by smr277** [comment]
Aha! You are awesome. (Granted, first install the pip protobuf dependency)
If you do the following, it works:
```
py_proto_compile(
	name = "my_proto",
	protos = ["my.proto"],
)

py_binary(
    name = "some_binary",
    srcs = [
        "some_file.py",
        ":my_proto"
    ],
    main = "some_main.py",
) ```
