### ISSUE TITLE
Closure Rules requires Bazel >=0.4.5 but was 0.10.1

### ISSUE THREAD

**Issue by goettl79** [pubref/rules_protobuf#186]
Tried to execute the examples with Bazel 0.10. Doesn't work. Seems to be a version comparison error, likely a string compare instead of a number compare. Don't know where yet.

**Comment by gramic** [comment]
Recently I transitioned my project to use the HEAD of rules_closure. It seems that problem is fixed there already.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
