### ISSUE TITLE
Upgrading gRpc to 1.9.1

### ISSUE THREAD

**Issue by junghoahnsc** [pubref/rules_protobuf#187]
Hello,

I'm trying to upgrade gprc to v1.9.1 by overriding dependencies.
I also added some dependencies in https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl (like protobuf_headers) manually since the current deps rule doesn't include them.

But I got the following error.

```
...
WARNING: /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_google_grpc_base/WORKSPACE:1: Workspace name in /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_google_grpc_base/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@com_google_grpc_base); this will cause a build error in future versions
ERROR: /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_google_grpc/third_party/cares/BUILD:37:1: rule 'ares_build_h' has file 'ares_build.h' as both an input and an output
...
```

I guess this might be related to symlinks by grpc_repository(). Is this a known issue?

Thanks,

**Comment by pcj** [comment]
Not by me.  I'll look into this but won't be able to get to it until mid- next week.
