### ISSUE TITLE
Trying to mutate a frozen object error

### ISSUE THREAD

**Issue by bowlofstew** [pubref/rules_protobuf#189]
`
bazel build //...

ERROR: /Users/shenderson/Desktop/code/uptake/data_science/uptake-platform/source/tagging-api/protos/BUILD:77:1
: Traceback (most recent call last):
        File "/Users/shenderson/Desktop/code/uptake/data_science/uptake-platform/source/tagging-api/protos/BUI
LD", line 77
                grpc_gateway_proto_library(name = "tag_messages_gateway_lib...", ..."])
        File "/private/var/tmp/_bazel_shenderson/0f1131633cf0c25e7d480bf35cb8e155/external/org_pubref_rules_pr
otobuf/grpc_gateway/rules.bzl", line 66, in grpc_gateway_proto_library
                go_proto_deps += GRPC_COMPILE_DEPS
trying to mutate a frozen object
`

Where the target, protocol_files is defined as

`
filegroup(
    name = "protocol_files",
    srcs = [
      "shared.proto",
      "file_tag.proto",
      "column_tag.proto",
      "row_tag.proto",
      "cell_tag.proto",
    ],
)

proto_library(
    name = "tagging_protos",
    srcs = [":protocol_files"],
    visibility = ["//visibility:public"],
    deps = [
        "@googleapis//:api_proto",
    ]
)
`

Bazel information:

`

bazel version
Build label: 0.10.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.ja
r
Build time: Tue Oct 11 20:06:37 +50095 (1518702897997)
Build timestamp: 1518702897997
Build timestamp as int: 1518702897997

`

**Comment by pcj** [comment]
Thanks for report.  Will get this fixed later this week unless you send PR first.

**Comment by bowlofstew** [comment]
@pcj I'd love to assist.  I'm pretty new to your codebase but if you can point me in the right direction here, I'll gladly jump in!

**Comment by pcj** [comment]
Look at https://github.com/pubref/rules_protobuf/commit/54dd1c1c7167fed1fb9c92d7f6f55ef908e93f85, same problem.

The issue  is that if you initialize an empty list as a function parameter here "go_proto_deps", if you then try to append to it, it fails (list was frozen).  Earlier versions of bazel didn't freeze input args like this.

**Comment by shanghai-Jerry** [comment]
@pcj  how to fix this frozen

**Comment by bowlofstew** [comment]
Awesome, thanks!

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
