### ISSUE TITLE
Importing v0.8.1 of rules_protobuf causes dependency conflict on com_github_protobuf

### ISSUE THREAD

**Issue by PranavSathy** [pubref/rules_protobuf#193]
I have a workspace file which contains the following contents:

```
workspace(name = "myworkspace")

# Load Go BUILD rules (v0.10.1)
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.10.1/rules_go-0.10.1.tar.gz",
    sha256 = "4b14d8dd31c6dbaf3ff871adcd03f28c3274e42abc855cb8fb4d01233c0154dc",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains", "go_repository")
go_rules_dependencies()
go_register_toolchains()

go_repository(
    name = "com_github_globalsign_mgo",
    tag = "r2018.02.20",
    importpath = "github.com/globalsign/mgo",
)

# ---------------------------------------------------------------------------

# Load Protobuf BUILD rules (v0.8.1)
git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.1",
)

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_repositories")
py_proto_repositories()
```

An existing repo_rule rule 'com_google_protobuf' was already loaded with a sha256 value of ''.  Refusing to overwrite this with the requested value ('e83ee63eccfb47f07f263fbcdea0a2d838dab4a750c53867013539b5e536dd8a').

I am attempting to use the python protobuf like so:
```
# Account Info protobuf BUILD definitions.
package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_library")

proto_library(
    name = "account_info_proto",
    srcs = ["account_info.proto"],
)

go_proto_library(
    name = "account_info_go_proto",
    proto = ":account_info_proto",
)

py_proto_library(
    name = "account_info_py_proto",
    proto = ":account_info_proto",
)
```

**Comment by PranavSathy** [comment]
It seems upgrading to "the latest commit" fixes this issue, I suppose the bundle from back in last september breaks the build:

git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  commit = "7c8c80b61e3a0bc30fd61302d781a317524b0167",
)

It seems that there is no longer a need for go_proto_library since rules_go supports this natively now, do we have thoughts on the subject?

**Comment by pcj** [comment]
I'll cut a new release to reduce confusion here.  

As far as the need for `go_proto_library`, I still need to check feature parity (such as protos in subdirectories, external workspaces, etc) before concluding that the one in this repo is not needed.

But, I think the roadmap for 1.0 should be to make all rules as similar to or identical to the native ones when possible, making `rules_protobuf` a shim-like library where native proto support has still not caught up.

**Comment by pcj** [comment]
Closiing this with https://github.com/pubref/rules_protobuf/releases/tag/v0.8.2 released.
