### ISSUE TITLE
Would love a new release that includes ff3b7e79!

### ISSUE THREAD

**Issue by brandon-rhodes** [pubref/rules_protobuf#199]
I help maintain a local build of Livegrep, and our version of Bazel now tries to be extra-efficient and perform only shallow checkouts of dependent projects — which means that I can't any longer just point at an arbitrary commit like ff3b7e79 as the version of rules_protobuf that I depend on. But if that commit, or any later commit, were given a tag name — whether a full release name, or a one-off tag name — then I could depend on that tag, and have a stable build again that didn't change every time rules_protobuf's `master` advances (I'm currently using `master`, just to have things working again).

If a release in the near term isn't possible then just let me know, because I have a backup plan: I can fork this repo and add a tag myself. But I thought I'd ask before taking that step. Thanks!

**Comment by pcj** [comment]
Apologies for delay @brandon-rhodes, closing this with the release of https://github.com/pubref/rules_protobuf/releases/tag/v0.8.2.  Pls re-open if you are still blocked on this.
