### ISSUE TITLE
Travis CI failing with GCC error

### ISSUE THREAD

**Issue by pcj** [pubref/rules_protobuf#2]
Getting this project on travis CI, fails while trying to build boringssl, a dependency of gRPC++.  

```sh
ERROR: /home/travis/.cache/bazel/external/boringssl/BUILD:91:1: C++ compilation of rule '@boringssl//:crypto' failed: gcc failed: error executing command 
  (cd /home/travis/.cache/bazel/execroot/rules_protobuf && \
  exec env - \
    PATH=/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/home/travis/.rvm/bin:/usr/lib/jvm/java-8-oracle/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF bazel-out/local-fastbuild/bin/external/boringssl/_objs/crypto/external/boringssl/src/crypto/aes/aes.pic.d -fPIC -iquote external/boringssl -iquote bazel-out/local-fastbuild/genfiles/external/boringssl -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/boringssl/src/include -isystem bazel-out/local-fastbuild/genfiles/external/boringssl/src/include -isystem external/bazel_tools/tools/cpp/gcc3 -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common '-std=c11' -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/boringssl/src/crypto/aes/aes.c -o bazel-out/local-fastbuild/bin/external/boringssl/_objs/crypto/external/boringssl/src/crypto/aes/aes.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
cc1: error: unrecognized command line option '-std=c11'
cc1: error: unrecognized command line option "-Wno-free-nonheap-object" [-Werror]
cc1: all warnings being treated as errors
INFO: Building complete.
INFO: Elapsed time: 148.165s, Critical Path: 7.32s
ERROR: No test targets were found, yet testing was requested.
The command "bazel \
  --output_base=$HOME/.cache/bazel \
  --batch \
  --host_jvm_args=-Xmx500m \
  --host_jvm_args=-Xms500m \
  test \
  examples/... \
  --verbose_failures \
  --test_output=errors \
  --test_strategy=standalone \
  --spawn_strategy=standalone \
  --genrule_strategy=standalone \
  --local_resources=400,1,1.0 \
  $FLAGS
" exited with 1.
```

@jcanizales I'm trying to get these rules to work in multiple languages, but c++ is not a language that I have much experience.  So I have to fake it a bit.  This is currently working on my osx workstation.  I humbly ask if you can take a look to see how I can configure this to build successfully on travis.   Is this something simple?

See From https://travis-ci.org/pubref/rules_protobuf/jobs/149826146

**Comment by pcj** [comment]
Looping in @korfuri who has experience with c++/travis/bazel too.  Thanks!

**Comment by korfuri** [comment]
`cc1: error: unrecognized command line option '-std=c11'` sounds like you are using an old, old g++. That's a common problem with Travis: its default gcc is quite old. I haven't used Bazel on Travis in a while, but IIRC the only way to make that work with Bazel is to provide a custom CROSSTOOL that specifies /usr/bin/g++-4.8 instead of just /usr/bin/g++ as the compiler.

See https://github.com/korfuri/bazel-travis/blob/master/tools/custom_crosstool/CROSSTOOL for instance for how I did it in my old bazel-travis demo.

There may be a much easier way nowadays, Bazel has evolved a lot since I last used it.

**Comment by jcanizales** [comment]
Hi Paul, no need to ask humbly, I'm very happy to help :) Although I don't think I'll be very useful in this specific situation. I do have Travis compiling a C++ gRPC server and it never gave me an issue. I haven't looked much inside the `Makefile` at the root of the https://github.com/grpc/grpc repo, but `make interop_server` triggers that build. It brings the BoringSSL sources from a submodule.

**Comment by jcanizales** [comment]
Ah, but now that I think about it my Travis build is on OS X, not Linux!

**Comment by pcj** [comment]
I'm now using the trusty beta "mega" image which is selected via `dist: trusty` + `sudo: required` flags.  This has more modern c++ toolchain incl. gcc4.8.  It appears to be building the grpc dependencies and boringssl without issue.   No custom CROSSTOOL needed.  

The client build is failing however with the following problem:  

```sh
ERROR: /home/travis/build/pubref/rules_protobuf/examples/helloworld/cpp/BUILD:55:1: Linking of rule '//examples/helloworld/cpp:client' failed: gcc failed: error executing command 
  (cd /home/travis/.cache/bazel/execroot/rules_protobuf && \
  exec env - \
  /usr/bin/gcc -o bazel-out/local-fastbuild/bin/examples/helloworld/cpp/client -Wl,-no-as-needed -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local-fastbuild/bin/examples/helloworld/cpp/client-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

It may be a botched attempt to abstract the client interface into a header file for use in a gtest by a non-c++ programmer (me).   Works on osx however.

@jcanizales @korfuri Does this still look like a toolchain problem or just bad C++ programming? 

https://travis-ci.org/pubref/rules_protobuf/jobs/151816356

**Comment by korfuri** [comment]
Just bad C++ programming here ;) you're missing a main() function.

In your "travis" branch, you commented the main() out of greeter_client.cc
when you split that to a cc_library instead of a cc_binary, but
//examples/helloworld/cpp:client (the new cc_binary) doesn't have a srcs
list. You should move the main() that is commented in greeter_client.cc to
another file, say greeter_client_main.cc, and add that file to the srcs of
:client.

**Comment by pcj** [comment]
Well that's a bit embarrasing!  Thanks for your help though, that did the trick. The build is passing now.  Closing this issue.
