### ISSUE TITLE
Fix gRPC workspace name

### ISSUE THREAD

**Issue by calder** [pubref/rules_protobuf#207]
Rename `com_google_grpc` to `com_github_grpc_grpc` to fix the following Bazel warnings:

```sh
WARNING: .../external/com_google_grpc/WORKSPACE:1: Workspace name in .../external/com_google_grpc/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@com_google_grpc); this will cause a build error in future versions
```

**Comment by pcj** [comment]
Actually I am remembering better now.  We use the grpc/grpc repo a little differently in this repo in that it gets cloned down as com_google_grpc_base, then do some surgery to the repo to install c_ares without cloning submodules (which is slow).

This should be resolved once https://github.com/pubref/rules_protobuf/pull/190 lands.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
