### ISSUE TITLE
Impossible to use same service definition for GRPC Gateway & non-Go lib

### ISSUE THREAD

**Issue by th0br0** [pubref/rules_protobuf#216]
GRPC Gateway usage requires an import of `google/api/annotations.proto`
However, the only way this is exported is via
```
        "@org_golang_google_genproto//googleapis/api/annotations:go_default_library",
```
which makes usage in non-Go targets impossible.

There should be an easy-to-use dependency to support such build cases.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
