### ISSUE TITLE
grpc_gateway_proto_library expects Gateway service definition for all proto files

### ISSUE THREAD

**Issue by th0br0** [pubref/rules_protobuf#217]
A target such as
```
grpc_gateway_proto_library(
    name="gateway",
    verbose=1,
    protos=["a.proto", "b.proto"],
    visibility=["//visibility:public"], )
```

Will expect output to
```
a.pb.gw.go
b.pb.gw.go
a.pb.go
b.pb.go
gateway.pb.descriptor_set
```
even though not all supplied proto files might contain valid (Gateway) service definitions.
If, for example, `b.proto` only contains messages, then no `b.pb.gw.go` output file is created by `protoc`

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
