### ISSUE TITLE
proto_library rule not found

### ISSUE THREAD

**Issue by sumedhsakdeo** [pubref/rules_protobuf#218]
I want to generate stubs for c++ and python and would like to use proto_library. However, I get this error.

file '@org_pubref_rules_protobuf//protobuf:rules.bzl' does not contain symbol 'proto_library'

Are there any plans on adding support for this rule, so that I can generate stubs for more than one language?

I tried using proto_compile for multiple languages and it works great!

**Comment by sumedhsakdeo** [comment]
Looks like if I add the following to cpp_proto_library() it generates protostubs for python and c++
langs = [
            “@org_pubref_rules_protobuf//python”,
            “@org_pubref_rules_protobuf//cpp”,
]

**Comment by bbarnes52** [comment]
+1 - are there plans to support dependencies on proto_library rules from py_proto_library?

seems like an anti-pattern to have to specify the .proto files in srcs attribute of more than one rule

**Comment by promiseofcake** [comment]
> +1 - are there plans to support dependencies on proto_library rules from py_proto_library?
seems like an anti-pattern to have to specify the .proto files in srcs attribute of more than one rule

This was built before proto_library was in the native rules. @pcj has mentioned that this repo's purpose has been to bridge the gap between desired functionality and missing functionality from the native rules. So I _believe_ (correct me if I am wrong) there are plans to move in this direction if the native `rules_*` teams don't include protobuf / gRPC compilation in their rules.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
