### ISSUE TITLE
Unable to depend on gogoproto/gogo.proto

### ISSUE THREAD

**Issue by superfell** [pubref/rules_protobuf#219]
I have a .proto that uses the gogo proto extensions in it, e.g. in the proto there's

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message Items {
	repeated Item item = 1 [(gogoproto.nullable)=false]; 
}

This proto defines a service i'm trying to call from python, e.g.

proto_library(
    name = "api_proto",
    srcs = ["api.proto"],
    deps = [
        "@com_google_protobuf//:timestamp_proto",
    ],
)

This gives an error about importing gogo.proto, i've followed the instructions to enable gogo proto, but unlike the com_google_protobuf module, it doesn't appear to export a proto_library for the gogo.proto file. e.g.

```
$ bazel query "kind("proto_library", @com_github_gogo_protobuf//...)"
INFO: Empty results
```

whereas the google one reports
```
$ bazel query "kind("proto_library", @com_google_protobuf//...)"
@com_google_protobuf//examples:addressbook_java_proto
@com_google_protobuf//examples:addressbook_java_lite_proto
@com_google_protobuf//examples:addressbook_cc_proto
@com_google_protobuf//examples:addressbook_proto
@com_google_protobuf//:wrappers_proto
@com_google_protobuf//:timestamp_proto
@com_google_protobuf//:struct_proto
@com_google_protobuf//:field_mask_proto
@com_google_protobuf//:empty_proto
@com_google_protobuf//:duration_proto
@com_google_protobuf//:compiler_plugin_proto
@com_google_protobuf//:descriptor_proto
@com_google_protobuf//:api_proto
@com_google_protobuf//:type_proto
@com_google_protobuf//:source_context_proto
@com_google_protobuf//:any_proto
```

How do i refer to the gogo.proto file for the deps section ?

**Comment by superfell** [comment]
After ffurther exploration i found this
https://github.com/bazelbuild/rules_go/pull/1170/files
However trying to use @gogo_special_proto doesn't seem to work either
proto_library(
    name = "api_proto",
    srcs = ["api.proto"],
    deps = [
        "@com_google_protobuf//:timestamp_proto",
        "@gogo_special_proto//github.com/gogo/protobuf/gogoproto:gogoproto",
    ],
)

gives
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
foo/api.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
