### ISSUE TITLE
Build fail when BUILD rule is not same directory with proto file

### ISSUE THREAD

**Issue by pdu** [pubref/rules_protobuf#220]
The following cannot work:

    cc_proto_library(
      name = "testlib",
      protos = ["src/test.proto"],
      with_grpc = True,
    )

The error msg is:

    INFO: Analysed target //:testlib (1 packages loaded).
    INFO: Found 1 target...
    ERROR: ~/dev/kvstore_grpc/BUILD:41:1: output 'test.pb.h' was not created
    ERROR: ~/dev/kvstore_grpc/BUILD:41:1: output 'test.pb.cc' was not created
    ERROR: ~/dev/kvstore_grpc/BUILD:41:1: output 'test.grpc.pb.h' was not created
    ERROR: ~/dev/kvstore_grpc/BUILD:41:1: output 'test.grpc.pb.cc' was not created
    ERROR: ~/dev/kvstore_grpc/BUILD:41:1: not all outputs were created or valid
    Target //:testlib failed to build

The following can work, if I put the build rule as the same directory as the proto file:

    cc_proto_library(
      name = "testlib",
      protos = ["test.proto"],
      with_grpc = True,
    )

How to fix this problem?

**Comment by promiseofcake** [comment]
We do something similar, and I believe if you pass a [filegroup](https://docs.bazel.build/versions/master/be/general.html#filegroup) to `protos` it will solve this despite not being the [recommended approach](https://blog.bazel.build/2017/02/27/protocol-buffers.html).

**Comment by pdu** [comment]
@promiseofcake Thanks, filegroup looks like a good idea. I will close the issue.
