### ISSUE TITLE
Is there a way I can choose the protobuf version?

### ISSUE THREAD

**Issue by yuanzhedong** [pubref/rules_protobuf#223]
On my dev machine(ubuntu 16.04) I recently installed protobuf system-wise and get this error:

```
This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.5.1)
```

Is there a way I can specify protobuf version in rules_protobuf so that my code will build with version 3.5.1? Thanks!

**Comment by yuanzhedong** [comment]
Here's my bazel config:

```
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf.git",
    tag = "v0.8.2",
)
```

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
