### ISSUE TITLE
output_file_style = "python" in proto_language

### ISSUE THREAD

**Issue by llchan** [pubref/rules_protobuf#224]
Could we add support for `output_file_style = "python"` in `proto_language`? Dashes in the filenames need to be converted to dashes to match the `protoc` logic.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
