### ISSUE TITLE
Add the ability to run protoc from a different root dir

### ISSUE THREAD

**Issue by llchan** [pubref/rules_protobuf#225]
When protoc-ing python libs, there are use cases where we don't want the full directory tree to be used in the module hierarchy. For example, if I have `foo/bar/baz.proto`, I might want `bar_pb2.py` and `bar_pb2_grpc.py` to be built relative to the `bar` parent dir. Instead of a `import foo.bar.baz_pb2`, it would then have a vanilla `import baz_pb2`.

This is more than a convenience factor, because if any of the parent directories have a dash in the name, the python lib generation fails.

A placeholder attr "root" is already present in `proto_compile`, but it's not hooked up to anything, is this what it's planned for?

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
