### ISSUE TITLE
Can't build GRPC when using cpp_proto_repositories

### ISSUE THREAD

**Issue by kerrick-lyft** [pubref/rules_protobuf#232]
I created a new directory and added a WORKSPACE file to it with these contents:
```
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf",
    tag = "v0.8.2",
)

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")

cpp_proto_repositories()

http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-f0375f86e94f9970283e80996e1326b4416ed4da",
    urls = [
        "https://github.com/grpc/grpc/archive/f0375f86e94f9970283e80996e1326b4416ed4da.tar.gz",
    ],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
```

However, when I then run `bazel build @com_github_grpc_grpc//:grpc`, it fails with this error:
```
$ bazel build @com_github_grpc_grpc//:grpc                            
..........
ERROR: /home/lyft/.cache/bazel/_bazel_lyft/fcef6627290da7f3aa70a15cdc8d84c6/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:26:5: no such target '@com_github_madler_zlib//:z': target 'z' not declared in package '' defined by /home/lyft/.cache/bazel/_bazel_lyft/fcef6627290da7f3aa70a15cdc8d84c6/external/com_github_madler_zlib/BUILD.bazel and referenced by '//external:zlib'
ERROR: Analysis of target '@com_github_grpc_grpc//:grpc' failed; build aborted: Loading failed
INFO: Elapsed time: 19.770s
FAILED: Build did NOT complete successfully (11 packages loaded)
```

It looks like something that `cpp_proto_repositories` is doing is preventing upstream GRPC from building correctly.

**Comment by kerrick-lyft** [comment]
By the way, I realize that `rules_protobuf` provides GRPC. In this case, we have a large monorepo that is using `rules_protobuf` in some places, but we'd like to start using upstream GRPC in some new projects.

**Comment by annasapek** [comment]
Moving the `load("@org_pubref_rules_protobuf//cpp:rules.bzl"...)` and `cpp_proto_respositories()` statements after the gRPC-related WORKSPACE configuration solves this issue for me (I'm also using v0.8.2 of rules_protobuf). 

However, when I try to build any target that depends on a `xx_proto_library` built by rules_protobuf, and a `@com_github_grpc_grpc`, I get compilation errors related to multiple definitions of the same gRPC symbols (one from `com_github_grpc_grpc` and one from `com_google_grpc`). I have a feeling that you will run into this as well given that you are importing your own version of gRPC...

Now I'm actually not sure if this repository supports using a custom version of gRPC in your project workspace. Any thoughts?

**Comment by kerrick-lyft** [comment]
This is no longer an issue for us because we removed `rules_protobuf` and are using Bazel's built-in rules.

**Comment by promiseofcake** [comment]
@kerrick-lyft, are you compiling gRPC as well with the built-in rules? What languages are you supporting?

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
