### ISSUE TITLE
Dart support?

### ISSUE THREAD

**Issue by GreenishBlue** [pubref/rules_protobuf#239]
Are you planning to add Dart support to this project?

Currently the official dart rules are in beta, but they works fairly well. It'd be a great benefit to those of us who develop in Dart across mobile and web.

**Comment by pcj** [comment]
Yes!  I'd like to see this.  I'm somewhat backlogged and have not had time to give all the issues in this repo adequate attention but I'm very interested in seeing dart support.

**Comment by GreenishBlue** [comment]
I may take a crack at this at some point and submit a PR.

**Comment by pcj** [comment]
There is a partially working dart implementation at stackb/rules_proto, contributions welcome.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
