### ISSUE TITLE
output can't be checked with cc_proto_library

### ISSUE THREAD

**Issue by junghoahnsc** [pubref/rules_protobuf#24]
I have a local repository with my our BUILD file.

```
new_local_repository(
    name = "pb_schema",
    path = __workspace_dir__ + "/pb_schema",
    build_file = "BUILD.pb_schema",
)

BUILD.pb_schema:

cc_proto_library(
    name = "proto",
    protos = ["a/b/c.proto"],
    deps = ["@protobuf//:cc_wkt_protos"],
    with_grpc = True,
    verbose=2,
)
```

But BUILD failed with
```
output 'external/pb_schema/c.pb.h' was not created.
...
```

The generated files are in `external/pb_schema/a/b/c.pb.h`

I also tried `new_local_repository` with `path = __workspace_dir__ + "/pb_schema/proto/snapmind",`, but it didn't work either

```
bazel-out/local-fastbuild/genfiles/external/pb_schema/c.grpc.pb.cc:5:45: fatal error: external/pb_schema/c.pb.h: No such file or directory
 #include "external/pb_schema/c.pb.h"
```

**Comment by pcj** [comment]
The expected generated file is currently based on the protofile basename rather than the short_path, but this should be a supported use case.

**Comment by pcj** [comment]
Should be fixed by cc4556cafef017a536d88245451be5a76673d762.  Can you confirm and close issue if it works for you?

**Comment by junghoahnsc** [comment]
I got the following error:

```
RROR: /usr/local/share/users/jungho.ahn/cache/bazel/_bazel_jungho.ahn/c8d993de066bb9ba420445c3170a1d5a/external/pb_schema/BUILD:17:1: in proto_compile rule @pb_schema//:snapcraft_proto.pb:
Traceback (most recent call last):
       	File "/usr/local/share/users/jungho.ahn/cache/bazel/_bazel_jungho.ahn/c8d993de066bb9ba420445c3170a1d5a/external/pb_schema/BUILD", line 17
       		proto_compile(name = 'snapcraft_proto.pb')
       	File "/usr/local/share/users/jungho.ahn/cache/bazel/_bazel_jungho.ahn/c8d993de066bb9ba420445c3170a1d5a/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 512, in _proto_compile_impl
       		_build_output_files(run, builder)
       	File "/usr/local/share/users/jungho.ahn/cache/bazel/_bazel_jungho.ahn/c8d993de066bb9ba420445c3170a1d5a/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 186, in _build_output_files
       		ctx.new_file("/".join(path))
external/pb_schema/./pb_schema/snapmind/snapcraft.pb.h.
ERROR: Analysis of target '@pb_schema//:snapcraft_proto' failed; build aborted.
```

WORKSPACE:
```
new_local_repository(
    name = "pb_schema",
    build_file = "BUILD.pb_schema",
    path = __workspace_dir__ + "/pb_schema/proto",
)
```

BUILD:
```
load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
     name = "snapcraft_proto",
     protos = ["snapmind/snapcraft.proto"],
     verbose = 2,
     with_grpc = True,
     deps = ["@protobuf//:cc_wkt_protos"],
)
```

**Comment by pcj** [comment]
OK, it'll look at it again :)  There are two uses cases here, I guess I just solved for the first one:

1. Invoking `protos = ["snapmind/snapcraft.proto"]` in own WORKSPACE.  

2. Invoking `protos = ["snapmind/snapcraft.proto"]` in an external WORKSPACE (like your example).

**Comment by pcj** [comment]
Want to try 4a764409728c21c82e5fd00a5740472dbec3ed37?  It's not merged on master.  Has a test example that you can refer to as well.

**Comment by junghoahnsc** [comment]
Thanks for the fix. It works!

BTW, when two local repositories have the same paths, how can I distinguish them in `#include`?
E.g., repository A and B has proto/a/b.proto and I'd like to include A's proto/a/b.pb.h.

I tried `#include "external/A/proto/a/b.pb.h"`. It seems to find it, but I got some unrelated errors like
```
In file included from model_server/server.cc:16:0:
bazel-out/local-fastbuild/genfiles/external/pb_schema/proto/snapcraft/snapcraft.grpc.pb.h:126:84: error: 'grpc::ServerUnaryStreamer' has not been declared
     virtual ::grpc::Status StreamedStylize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::snapcraft::StylizationRequest,::snapcraft::StylizationResponse>* server_unary_streamer) = 0;
```

**Comment by pcj** [comment]
What does your cc_library rule look like?  Does it depend on both A and B's proto_library rule?

**Comment by junghoahnsc** [comment]
For now, the cc_library depends on only A. But I'm just curious when cc_library depends on both.

**Comment by pcj** [comment]
I have not tried it, but I would imagine that one would have to disambiguate the names somehow.  Since the name of #include file would be the same (does not incorporate the workspace name A|B), would be confusing.  

In that case perhaps a genrule to cp the proto file to a new namespace might work.

Glad to hear the fix worked.  Thanks for your testing and feedback.
