### ISSUE TITLE
using imports in py_proto_compile fails: _pb2.py and pb2_grpc.py not created

### ISSUE THREAD

**Issue by haikalpribadi** [pubref/rules_protobuf#245]
Hi,

We have 3 proto files which depend on each other, sitting in `//protocol/proto` package. Basically:
```
//protocol/
    |__ proto/
        |__ `A.proto` # depends on: `B.proto`, `C.proto`
        |__ `B.proto` # depends on: `C.proto`
        |__ `C.proto`
```
Inside `A.proto`, we declare, `imports B.proto` and `imports C.proto`, WITHOUT the prefix `protocol/path` to the file names.

For Java code compilation (in `//protocol/BUILD`), we use `imports` like the following, and the rule works perfectly.
```
java_proto_compile(
  name = "client-java-proto",
  protos = glob(["proto/*.proto"]),
  imports = ["protocol/proto"],
  with_grpc = True,
)
```

However, when I try to do the same for Python code compilation (also in `//protocol/BUILD`), it does not work:
```
py_proto_compile(
  name = "client-python-proto",
  protos = glob(["proto/*.proto"]),
  imports = ["protocol/proto/"],
  with_grpc = True,
)
```
`bazel build //protocol:client-python-proto` returns the following error:
```
ERROR: ~/protocol/BUILD:31:1: output 'protocol/proto/A_pb2.py' was not created
ERROR: ~/protocol/BUILD:31:1: output 'protocol/proto/A_pb2_grpc.py' was not created
ERROR: ~/protocol/BUILD:31:1: output 'protocol/proto/B.py' was not created
ERROR: ~/protocol/BUILD:31:1: output 'protocol/proto/B_pb2_grpc.py' was not created
ERROR: ~protocol/BUILD:31:1: output 'protocol/proto/C_pb2.py' was not created
ERROR: ~/protocol/BUILD:31:1: output 'protocol/proto/C_pb2_grpc.py' was not created
ERROR: ~/protocol/BUILD:31:1: not all outputs were created or valid
Target //protocol:client-python-proto failed to build
```

Importing the full path of the imported proto files (e.g. `import protocol/proto/A.proto`) fixes this, but it's important for us that we don't add the full path as the prefix. Thus we're trying to make the `imports` argument work.

Do you have an idea what could be the cause and how we can work around this?

_ps: I'd be happy to help work on a PR if that helps pick things up!_

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
