### ISSUE TITLE
Update rules_protobuf to rules_go 0.16.0

### ISSUE THREAD

**Issue by katre** [pubref/rules_protobuf#248]
This will involve removing the use of go_prefix in the rules.

See release notes for rules_go: https://github.com/bazelbuild/rules_go/releases/tag/0.16.0
Note on the deprecation and removal of go_prefix: https://github.com/bazelbuild/rules_go/issues/721

Note that rules_protobuf not updating holds back any project that depends on rules_protobuf.

**Comment by pcj** [comment]
Hi @katre I've pretty much totally rewritten these rules to layer on top of native.proto_library rule, now under a new organization.  Still working on the documentation but they use a recent version of rules_go.  There are a few features not included there but overall the rules are much simpler.  I'd consider migrating to them.  Hope that's not too disruptive.

https://github.com/stackb/rules_proto

**Comment by katre** [comment]
Hmm, this isn't actually my project I'm migrating, but I'll give it a shot, thanks.

**Comment by mhlopko** [comment]
Hi Paul,
does it mean that these rules_protobuf are deprecated/unmaintained?

**Comment by katre** [comment]
@pcj I took a look at stackb/rules_proto, and I can't even build that (looks like there's a local_repository in the WORKSPACE for your own copy of rules_dotnet, and I can't figure out a online version to use).

**Comment by mhlopko** [comment]
Can we get this PR merged here then?

**Comment by pcj** [comment]
This is an issue, not a PR.  I'll create a PR on rules_k8s to update the protobuf rules.
