### ISSUE TITLE
Addition of protoc-gen-grpc-web

### ISSUE THREAD

**Issue by xor-gate** [pubref/rules_protobuf#249]
It would be nice to see the github.com/grpc/grpc-web protoc-gen-grpc-web tool to be added which generates javascript code for use in-browser.

**Comment by pcj** [comment]
These rules have been rewritten and still undergoing some flux, and I have them under a new organization now 'stackb'.  Includes protoc-gen-grpc-web:

https://github.com/stackb/rules_proto/tree/master/github.com/grpc/grpc-web

**Comment by xor-gate** [comment]
Thanks for pointing to this!
