### ISSUE TITLE
32-bit C++ compilation

### ISSUE THREAD

**Issue by meme** [pubref/rules_protobuf#250]
When compiling a 32-bit application, the following happens (snippet):

```
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf/utility.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf/json_util.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf/message_differencer.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf/time_util.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf/type_resolver_util.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf/wire_format.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf/wrappers.pb.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf_lite/arena.pic.o: incompatible target
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf_lite/arenastring.pic.o: incompatible target
...
```

A `file` on one of these `.o` files shows that they are in fact compiled to x86_64 regardless of the fact that `env CC="/usr/bin/gcc" CFLAGS=-m32 CXX="/usr/bin/g++" CXXFLAGS=-m32 bazel build` is run (this _should_ perform 32-bit compilation).

In the `cc_library` section of my `BUILD` file I have specified to use 32-bit compilation:

```bzl
load("@org_pubref_rules_protobuf//cpp:rules.bzl", "GRPC_COMPILE_DEPS")

cc_binary(
  name = "example",
  srcs = glob(["*.cpp", "*.h"]),
  copts = ["-m32"],
  linkopts = ["-m32", "-L/usr/lib32"],
  deps = [
    "//proto",
  ] + GRPC_COMPILE_DEPS,
)
```

How can I adapt the compilation scripts used for gRPC and its dependencies to achieve a 32-bit build of my binary?

**Comment by meme** [comment]
Got it working using my fork, with the following command line options:
`CC=/usr/bin/gcc CPP=/usr/bin/g++ bazel build --copt=-m32 --cxxopt=-m32 --linkopt=-m32`

**Comment by pcj** [comment]
This is interesting, thanks.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
