### ISSUE TITLE
Python support requires pip or pypi

### ISSUE THREAD

**Issue by pcj** [pubref/rules_protobuf#3]
In order to support python fully in rules_protobuf, support for pulling dependencies from pip or pypi is required.  This is non-trivial for grpc as there is c-compilation involved with package installation.  Requires https://github.com/bazelbuild/bazel/issues/699 or similar.

**Comment by pcj** [comment]
Watching https://github.com/gengo/rules_pypi.

**Comment by pcj** [comment]
Now watching https://github.com/bazelbuild/rules_python/pull/1

**Comment by mattmoor** [comment]
@pcj Can you try this out and make sure it works for your use case?

As an avid Bazel-er, I'd love your feedback on the general workflow (e.g. the pattern for using `requirements.txt` as-is to bridge the world of Python idiomatic with Bazel).  I've been debating something similar for Node.js and `package-lock.json`.

**Comment by pcj** [comment]
@mattmoor Sure happy to.  

One nit I saw was in https://github.com/mattmoor/rules_python/tree/07fba0f91bb5898d19daeaabf635d08059f7eacd where `load("//python:pip.bzl", "pip_repositories")` should read `load("//@io_bazel_rules_python//python:pip.bzl", "pip_repositories")`

**Comment by pcj** [comment]
As far as general workflow, I like it.  I implemented a similar 2-stage loading pattern in `https://github.com/pubref/rules_maven` that I think will become common in bazel eventually.

**Comment by pcj** [comment]
@mattmoor Worked great!  I've pushed a new PR to this repo that uses your new rules and adds grpcio support here for python.  

I'll let this PR simmer for a bit until you and Damien work through your PR and update/merge it once you push those rules to master.  

I'll took a look as well but didn't see anything to comment on, so it's good IMHO.
