### ISSUE TITLE
How to override deps version?

### ISSUE THREAD

**Issue by junghoahnsc** [pubref/rules_protobuf#40]
Hello,

I have a build error because Go rule depends on old version of gRPC while
others like Google cloud API requires higher version.

https://github.com/pubref/rules_protobuf/blob/master/go/deps.bzl

Is there anyway to override this?

Thanks,

**Comment by junghoahnsc** [comment]
I think I can do by passing deps to `go_proto_repositories(lang_deps=deps)`.
But v0.7.1 will also fix my issue since it is using a higher grpc version.

**Comment by pcj** [comment]
Tagged latest release v0.7.1.  Feel free t re-open this if still having issues.

**Comment by junghoahnsc** [comment]
Thanks, it works! 

But I still need to override the dependency since I have to use a new feature of
golang/protobuf https://github.com/golang/protobuf/commit/cf10ca0ea91371dd30946defd93a0ed43aa1efe7 :)
