### ISSUE TITLE
Update grpc dep to v1.0.4

### ISSUE THREAD

**Issue by douglas-reid** [pubref/rules_protobuf#46]
Trying to build a go_proto_library with_grpc, got:

`undefined: grpc.SupportPackageIsVersion4`

This was fixed by manually adding:

```
new_go_repository(
    name = "org_golang_google_grpc",
    commit = "8712952b7d646dbbbc6fb73a782174f3115060f3",
    importpath = "google.golang.org/grpc",
)
```

to my WORKSPACE.

I believe the issue is that https://github.com/pubref/rules_protobuf/blob/master/go/deps.bzl#L26 is set to `"tag": "v1.0.2"` (instead of `"tag": "v1.0.4"` as needed).

From: https://github.com/grpc/grpc-go/releases/tag/v1.0.4

` Now the grpc support version is SupportPackageIsVersion4`

**Comment by pcj** [comment]
Thanks @douglas-reid, required updating golang/protobuf as well as grpc/grpc-go for SupportPackageIsVersion4.  Please re-open if you are still encountering issues.  PR's also welcome in the future to get you in the contributors list.

**Comment by douglas-reid** [comment]
Many thanks, @pcj !  Switched to your latest commit and everything works.

You got to it before I could even get around to starting a PR to confirm the fix.
