### ISSUE TITLE
GRPC shouldn't be required if you don't use it

### ISSUE THREAD

**Issue by pmbethe09** [pubref/rules_protobuf#48]
Simple proto of the form:

load("@com_github_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
    name = "cards_proto_cc",
    protos = ["cards.proto"],
)

Should not fail on:
no such package '@com_github_grpc_grpc//'

This dependency should only be sucked in when 'grpc_plugin' is set to something.

**Comment by pmbethe09** [comment]
Apparently I needed 
with_grpc = False,

I would have thought 'False' should be the default value for that field.

But then:
no such target '//external:protoc_gen_grpc_cpp': target 'protoc_gen_grpc_cpp'

Same thing -- this should not be needed when I set 'with_grpc' to False.

**Comment by pcj** [comment]
I agree this is suboptimal.  The architectural decision to include both grpc and non-grpc metadata in the [proto_language](https://github.com/pubref/rules_protobuf/blob/master/cpp/BUILD#L5-L19) rule entangles these concepts.  I will need to think about how to address this and don't have a satisfactory answer at the moment.

**Comment by pmbethe09** [comment]
I like when all I have to do is 'use_grpc = True' or similar.
Somehow there needs to be a clean check in the macro layer and make sure
that no gRPC labels are passed to the rule layer, otherwise resolution is
required.

**Comment by thaidn** [comment]
I can't tell if this is related, but cc_proto_library fails to compile if with_grpc is false:

$bazel build proto:cpp
INFO: Found 1 target...
ERROR: /home/test/blah/proto/BUILD:11:1: C++ compilation of rule '//proto:cpp' failed: linux-sandbox failed: error executing command /home/test/blah/.cache/bazel/_bazel_test/0fb2f33edd989c698a85a6fc0489350b/execroot/k2/_bin/linux-sandbox ... (remaining 47 argument(s) skipped).
In file included from bazel-out/local-fastbuild/genfiles/proto/k2.grpc.pb.cc:6:0:
bazel-out/local-fastbuild/genfiles/proto/k2.grpc.pb.h:12:46: fatal error: grpc++/impl/codegen/async_stream.h: No such file or directory
 #include <grpc++/impl/codegen/async_stream.h>
                                              ^
compilation terminated.
Target //proto:cpp failed to build

$ cat proto/BUILD 
package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")
load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

filegroup(
    name = "protos",
    srcs = ["myproto.proto"],
)

cc_proto_library(
    name = "cpp",
    protos = [":protos"],
    verbose = 0,
    with_grpc = False,
    imports = [
      "external/com_github_google_protobuf/src/",
    ],
    inputs = [
      "@com_github_google_protobuf//:well_known_protos",
    ],
)

java_proto_library(
    name = "java",
    protos = [":protos"],
    verbose = 0,
    with_grpc = False,
    imports = [
      "external/com_github_google_protobuf/src/",
    ],
    inputs = [
      "@com_github_google_protobuf//:well_known_protos",
    ],
)

bazel build proto:java works just fine though.

Ideas?

PS: thank you for releasing this tool. It has saved me many hours!

**Comment by pcj** [comment]
@thaidn Thanks for reporting this.  I'm looking into it now.

**Comment by pcj** [comment]
I think I see the problem.  I've moved your issue to #50 to close it with #51, but the larger issue raised by @pmbethe09 is still present.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
