### ISSUE TITLE
consider renaming proto.descriptor_set output file to proto.descriptor

### ISSUE THREAD

**Issue by perezd** [pubref/rules_protobuf#56]
Tools like gcloud service-management that make use of proto descriptors are opinionated about what the filename extensions are.  Supported extensions are .json .yaml .yml .pb. and .descriptor.
.descriptor is probably the best choice.

**Comment by perezd** [comment]
actually I think proto.pb.descriptor would be ok.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
