### ISSUE TITLE
Depends on a proto lib with well known protos

### ISSUE THREAD

**Issue by junghoahnsc** [pubref/rules_protobuf#59]
Hello,

I have a proto lib A that imports descriptor.proto and a proto lib B that depends on A.

```
go_proto_library(
    name = "a_proto_go",
    importmap = {
        "google/protobuf/descriptor.proto": "github.com/golang/protobuf/protoc-gen-go/descriptor",
    },
    imports = [
        "../../external/com_github_google_protobuf/src",
    ],
    protos = ["x/a.proto"],
    deps = [
      "@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library",
    ],
)

go_proto_library(
    name = "b_proto_go",
    protos = ["x/b.proto"],
    deps = [
        ":a_proto_go",
    ],
)
```

I could compile `a_proto_go`, but for `b_proto_go` I had to add the same `imports` to compile.
Is this expected? Is there any way to use the `imports` of the dependencies automatically?

Thanks,

**Comment by pcj** [comment]
Hi @junghoahnsc thanks, I agree these should transitively propagate. Will plan to fix.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
