### ISSUE TITLE
grpc_gateway_proto_library fails when property 'with_grpc' exists

### ISSUE THREAD

**Issue by prestonvanloon** [pubref/rules_protobuf#65]
```python
grpc_gateway_proto_library(
  name = "protolib",
  protos = ["message.proto"],
  with_grpc = True,
)
```
Fails when trying to build:
```
no such attribute 'with_grpc' in 'go_library' rule.
```

**Comment by pcj** [comment]
In the `grpc_gateway/rules.bzl`, the `grpc_gateway_proto_library` macro does not have the option as `with_grpc` is always assumed to be `True`.  All other options are passed as-is to the internal `go_library` rule via `**kwargs`.  

So, while somewhat confusing (and at the minimum underdocumented), this is working as intended.
