### ISSUE TITLE
In /examples `bazel run go/client` fails on linux

### ISSUE THREAD

**Issue by bzz** [pubref/rules_protobuf#69]
This might be a naive question but following the [/examples](https://github.com/pubref/rules_protobuf#examples):

 -  cpp/server built and run through CLI
 -  `bazel run go/client` fails

   ```
ERROR: /home/xxx/.cache/bazel/_bazel_xxx/68bdc85a7d4d2b9ce1849afc06064a21/external/io_bazel_rules_go/go/toolchain/BUILD:5:1: no such package '@io_bazel_rules_go_toolchain//': Not a file: /home/xxx/.cache/bazel/_bazel_xxx/68bdc85a7d4d2b9ce1849afc06064a21/external/golang_linux_amd64/BUILD and referenced by '@io_bazel_rules_go//go/toolchain:toolchain'.
ERROR: Analysis of target '//examples/helloworld/go/client:client' failed; build aborted.
INFO: Elapsed time: 0.133s
ERROR: Build failed. Not running target
   ```

There is `/home/xxx/.cache/bazel/_bazel_xxx/68bdc85a7d4d2b9ce1849afc06064a21/external/golang_linux_amd64` but indeed there is no BUILD file in there.

Would appreciate if somebody can point to the right docs, in case I'm doing something wrong here.

**Comment by pcj** [comment]
`rules_go` [dropped support of bazel < 0.4.4](https://github.com/bazelbuild/rules_go/blob/master/.travis.yml#L14-L15), so confirm you have recent `bazel`, and `rules_protobuf` from `HEAD`.

**Comment by bzz** [comment]
Thank you for pointing that out!

Running Go helloworld example with Bazel
```
$bazel version     

Build label: 0.4.4- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 10 17:35:16 2017 (1486748116)
```
built from [official release 0.4.4](https://github.com/bazelbuild/bazel/releases/) and the latest master of `rules_protobuf` 50a641aa3203aebadc5d8d3cd0d93f580a334d0b does not work for me on linux (\wo sandbox), resulting in an error above.

Tried running the same \w latest HEAD build of Bazel and got same error.

Is there anything else I could try to find out the reason?

**Comment by bzz** [comment]
Updating `rules_go` to a more recent https://github.com/bazelbuild/rules_go/commit/76c63b5cd0d47c1f2b47ab4953db96c574af1c1dhttps://github.com/bazelbuild/rules_go/commit/76c63b5cd0d47c1f2b47ab4953db96c574af1c1d inside the [WORKSPACE](https://github.com/pubref/rules_protobuf/blob/master/WORKSPACE#L9) did the trick.

This + local changes to workaround #67 allowed to run examples. 
@pcj please let me know if that is the right way and shall I submit a PR.

Or is there a reason why `rules_go` version in WORKSPACE is not a recent one?

**Comment by pcj** [comment]
Unless I'm mistaken, If `rules_protobuf` is updated to the most recent version of `rules_go`, it implies dropping support of bazel < 0.4.4.

**Comment by pcj** [comment]
Please re-open if still active, thanks.
