### ISSUE TITLE
Unable to build `cc_proto_library` with GRPC support on Ubuntu

### ISSUE THREAD

**Issue by nelhage** [pubref/rules_protobuf#7]
If I try to build a simple `cc_proto_library` with GRPC support (I'm copy-pasting the example from `bzl/cpp/README.md`, the build fails because the `com_github_grpc_grpc` build fails:

```
[nelhage@monomorphique:~/code/grpc-test]$ bazel build :protolib
INFO: Found 1 target...
ERROR: /home/nelhage/.cache/bazel/_bazel_nelhage/809c45c005e5377cc317259ef3196039/external/com_github_grpc_grpc/BUILD:159:1: C++ compilation of rule '@com_github_grpc_grpc//:grpc' failed: linux-sandbox failed: error executing command /home/nelhage/.cache/bazel/_bazel_nelhage/809c45c005e5377cc317259ef3196039/execroot/grpc-test/_bin/linux-sandbox ... (remaining 61 argument(s) skipped).
In file included from external/com_github_grpc_grpc/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.c:36:0:
external/com_github_grpc_grpc/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.h:38:35: fatal error: third_party/nanopb/pb.h: No such file or directory
compilation terminated.
Target //:protolib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 32.042s, Critical Path: 8.64s
```

I *believe* this is a symptom of https://github.com/grpc/grpc/issues/6728 but is there some workaround that allows this repository to work? I could vendor `nanopb` into my own `third_party` directory, but (a) that's fairly dissatisfying and (b) I'm not clear I won't run into other failures.

**Comment by pcj** [comment]
I'll start investigating this in docker. What's your environment?

**Comment by nelhage** [comment]
Linux, Ubuntu 14.04 Xenial, running bazel 0.3.1 from the official apt repository

**Comment by nelhage** [comment]
Sorry, I think https://github.com/grpc/grpc/issues/6083 may be the more relevant issue, but in either case the query of whether there's a minimally-invasive workaround stands. Thanks for looking into it!

**Comment by pcj** [comment]
Currently works on debian/jessie but failing as you report on Ubuntu Xenial 16.04.  Current (unsatisfactory) workaround is to use debian.

**Comment by nelhage** [comment]
That's fascinating and pretty confusing, and suggests gcc-4.8 vs. 5.x as the possible culprit, although I'm struggling to figure out how that could affect this. But it does give me something to dig into. I'll report back if I uncover anything.

**Comment by nelhage** [comment]
Ah-ha, I think I figure it out. It's a sandbox thing. The build will work if the sandbox is disabled (which [it is in travis](https://github.com/pubref/rules_protobuf/blob/master/.travis.yml#L43)), and I'm guessing your jessie doesn't support the sandbox for some reason.

The `grpc` checkout includes `third_party/nanopb`, so the files are available from that path, but because `//external:nanopb` is bound elsewhere, there isn't a declared dependency there. So with sandbox enforcing, bazel doesn't bring those files into the sandbox, and the compiler can't find it. With the sandbox disabled, the compiler picks them up even though they're undeclared.

That at least gives me a workaround for the moment. I'm hopeful that grpc/grpc#6851 will fix properly.

**Comment by pcj** [comment]
Nice pickup about the sandbox!  I've added a note on the README.md about this.  Will keep this issue open for now.
