### ISSUE TITLE
Support java_lite_proto_library

### ISSUE THREAD

**Issue by thaidn** [pubref/rules_protobuf#74]
I want to use lite proto for some Android project.

I can send a PR, but I need some guidance on where I should look at and change.

Thanks!

**Comment by thaidn** [comment]
Will this just work if I add

option optimize_for = LITE_RUNTIME;

to my .proto files?

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
