### ISSUE TITLE
gRPC version update

### ISSUE THREAD

**Issue by jylin** [pubref/rules_protobuf#75]
The current Java libraries are using gRPC v1.0.1, when gRPC v1.2.0 has recently be released. Some useful improvements include "waitForReady()" support on stubs. What is the expected time for a bump in version of the libraries?

**Comment by pcj** [comment]
Thanks @jylin, the java gRPC libraries seem to be much easier to upgrade than others such as C/C++ ones.  

If you're up for a PR, try updating the `java/deps.bzl` file and re-running the tests.

**Comment by lightyang** [comment]
I was able to [upgrade to 1.2.3  for C++](https://github.com/lightyang/rules_protobuf/tree/dev)... with some hacks
The main roadblock is [this issue](https://github.com/grpc/grpc/issues/10596)

**Comment by dmitry-xnor** [comment]
GRPC has also added a dependency on Ares DNS resolver, which further complicates things. I spent half a day today trying to upgrade to latest: no luck. Some deep and obscure stacktraces from Bazel was all I got in the end.

**Comment by pcj** [comment]
Finally implemented in #119, see https://github.com/pubref/rules_protobuf/blob/master/cpp/grpc_repository.bzl#L32
