### ISSUE TITLE
grpc_gateway rules don't work with 1.2 release of grpc-gateway

### ISSUE THREAD

**Issue by achew22** [pubref/rules_protobuf#77]
Unfortunately I don't have time to fix this right now but it's almost certainly because of [this commit](https://github.com/grpc-ecosystem/grpc-gateway/commit/0c0b378a74040eeb5ef415c5289258a193be0e94). grpc-gateway switched to genproto for our proto-go files. The changes described in the makefile need to be made here as well before grpc-gateway 1.2 will work with rules_protobuf.

**Comment by pcj** [comment]
Thanks Andrew I'll take a look.
