### ISSUE TITLE
py_proto_compile fails to correctly specify output for subdirectories

### ISSUE THREAD

**Issue by toffaletti** [pubref/rules_protobuf#78]
See example here: https://github.com/toffaletti/proto_fail

```
py_proto_compile(
    name = "py_options_proto",
    protos = ["models/options.proto"],
    with_grpc = False,
    visibility = ["//visibility:public"],
)
```

> ERROR: proto_fail/BUILD:2:1: output 'options_pb2.py' was not created.
ERROR: proto_fail/BUILD:2:1: not all outputs were created or valid.

`protoc` mirrors the input directory hierarchy and creates the output in `models/options_pb2.py`

**Comment by pcj** [comment]
Thanks for the report.  Probably will have to look closer at https://github.com/pubref/rules_protobuf/blob/master/protobuf/internal/proto_compile.bzl#L143-L163 in the case of python (or perhaps numerous languages when src label is not in the current directory as the BUILD file).

**Comment by pcj** [comment]
FYI this only seems to occur when the py_proto_compile rule is in root BUILD file (the BUILD file in the same directory as the WORKSPACE)...

**Comment by andrewmchen** [comment]
Ran into this issue today when generating `py_proto_library` in a directory with a `-` in it. Fix was to remove the `-`.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
