### ISSUE TITLE
go_proto_library fails when 'imports' is specified.

### ISSUE THREAD

**Issue by swsnider** [pubref/rules_protobuf#8]
If you change the rule in examples/helloworld/proto/BUILD to read:

```python
go_proto_library(
    name = "go",
    protos = ["helloworld.proto"],
    imports = ["examples/helloworld/proto"],
    verbose = 0,
    with_grpc = True,
)
```

then when you run `bazel test //examples/helloworld/go/greeter_test`, you get the error:

```
INFO: Found 1 test target...
ERROR: /Users/swsnider/rules_protobuf/examples/helloworld/proto/BUILD:18:1: declared output 'examples/helloworld/proto/helloworld.pb.go' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /Users/swsnider/rules_protobuf/examples/helloworld/proto/BUILD:18:1: not all outputs were created.
Target //examples/helloworld/go/greeter_test:greeter_test failed to build
```

I notice that the genfiles dir has the generated pb.go files at the top level, rather than inside the correct directory, but this might be a red herring.

**Comment by pcj** [comment]
In this case one should not need this import statement, but I agree the rule should either not fail or give a better error message.  I'll start looking into it.

**Comment by swsnider** [comment]
I totally agree, but I have a situation where I have a need for the import statement, and this was just the minimal test case :).

**Comment by pcj** [comment]
I've changed `go_proto_library` from a genrule to rule implementation internally which should solve the issue you reported.  Please try the v0.3.5 release.

However, there is still fairly poor support for imports.  Will be working on that in the near term.

**Comment by pcj** [comment]
The v0.4.0 release https://github.com/pubref/rules_protobuf/releases/tag/v0.4.0 makes imports much better.  Please try it out and either continue this thread or close it if resolved.  Grats!

**Comment by swsnider** [comment]
Thanks, but now I get a different error: #12. I assume that imports works better now, so I'll close this one.
