### ISSUE TITLE
Getters not included for proto messages

### ISSUE THREAD

**Issue by macrael** [pubref/rules_protobuf#83]
I'm seeing a different result compiling a proto file with rules_protobuf than I get if I run protoc manually. My messages are not generating getters for any members except for "repeated" ones. The docs (and protoc run by hand) say that getters should be generated for all members on messages, what could be going on? I'm seeing this wether I build with go_proto_library and go_proto_compile. I'm not passing any options.

**Comment by macrael** [comment]
This is reproducible with a bare bones config. Just the basic stuff in the readme docs and a single protobuf file with a single message in it.

**Comment by macrael** [comment]
I've made a sample project that reproduces the issue: https://github.com/macrael/bazel_go_protobuf_getters_missing

**Comment by pcj** [comment]
Few questions: 

1. What is the version of `protoc` run manually?
2. What is the version of `protoc-gen-go` in your path?
3. Is the result different if you call the protoc embedded in rules_protobuf directly? like:

```sh
$ bazel run @com_github_google_protobuf//:protoc -- foo.proto
```

**Comment by macrael** [comment]
protoc --version
libprotoc 3.2.0

Not sure how to determine the version of protoc-gen-go, I go get'd it this morning. protoc-gen-go does seem to be the culprit though. 

`bazel-bin/external/com_github_google_protobuf/protoc --go_out=. foo.proto`

includes the GetMessage method, while 

`bazel-bin/external/com_github_google_protobuf/protoc --plugin=protoc-gen-go=bazel-out/host/bin/external/com_github_golang_protobuf/protoc-gen-go/protoc-gen-go  --go_out=. foo.proto`

Does not include them.

**Comment by pcj** [comment]
Probably the go deps need to be updated.  First, can you try off the latest rules_protobuf commit and not 0.7.1?

Here are the go deps:

https://github.com/pubref/rules_protobuf/blob/master/go/deps.bzl

To test it, define the updated golang/protobuf repo in your WORKSPACE, somelhing like 

```python  
new_go_repository(
  name = "com_github_golang_protobuf",
  importpath = "github.com/golang/protobuf",
  commit = "2bba0603135d7d7f5cb73b2125beeda19c09f4ef", 
)

# Exclude rules_protobuf from loading it
go_proto_repositories(
  excludes = ["com_github_golang_protobuf"],
)
```

However, may require updating the other deps too...

**Comment by macrael** [comment]
Updating to the latest commit (d6c85ce9c36eb352aad5122f57a69e0ebdcc904a) of https://github.com/pubref/rules_protobuf fixed this issue for me. 

I'm surprised there isn't more visibility of this issue, it seems pretty basically broken right now. I'm curious what the fix was?

**Comment by macrael** [comment]
Thank you for being so responsive

**Comment by pcj** [comment]
0.7.1 is actually relatively old.  Should cut a new release.
