### ISSUE TITLE
Protobuf rule with Imports in External Project

### ISSUE THREAD

**Issue by Dig-Doug** [pubref/rules_protobuf#91]
I'm having an issue using a protobuf rule (with imports) in an external project. Here's what I have:

- libproject: Library with a public proto rule with an import of google.protobuf.Timestamp
- mainproject: Depends on the library, trying to use the proto rule in the libproject

When I try to build the mainproject, I get the following error:
```
/external/libproject/src/main/proto/BUILD:7:1: error executing shell command: 'cd external/libproject && ../../bazel-out/host/bin/external/com_github_google_protobuf/protoc --descriptor_set_out=../../bazel-out/local-fastbuild/genfiles/external/libproject/src/main/proto/test.p...' failed: bash failed: error executing command 
  (exec env - \
  /bin/bash -c 'cd external/libproject && ../../bazel-out/host/bin/external/com_github_google_protobuf/protoc --descriptor_set_out=../../bazel-out/local-fastbuild/genfiles/external/libproject/src/main/proto/test.pb.descriptor_set --java_out=../../bazel-out/local-fastbuild/genfiles/external/libproject/src/main/proto/test.pb_java.jar --plugin=protoc-gen-grpc-java=../../bazel-out/host/genfiles/external/org_pubref_rules_protobuf/java/protoc_gen_grpc_java --grpc-java_out=../../bazel-out/local-fastbuild/genfiles/external/libproject/src/main/proto/test.pb_java.jar --proto_path=external/com_github_google_protobuf/src/ --proto_path=. src/main/proto/test.proto'
```

I created a test repo that replicates my issue [here](https://github.com/Dig-Doug/externalprotoruletest).

I think the error is caused by an incorrect import path. Because the command cds into "external/libproject" to build, the "--proto_path=external/..." import path doesn't work properly as external/ only exists in the main build folder.

I came up with a [fix](https://github.com/Dig-Doug/rules_protobuf/commit/546aafeb6afc03a59cc805d748e7fdeeda1f0455) that looks for imports starting with 'external' and updates them with the correct path. However, I am not sure if this is the best way to fix the issue. Let me know if you have any improvements or suggestions - I am happy to work on this and submit a pull request once it looks good.

Thanks!

**Comment by bocon13** [comment]
This should probably be closed now

**Comment by Dig-Doug** [comment]
Fixed.
