### ISSUE TITLE
Allow grpc_gateway_proto_library deps for grpc_gateway_binary in place of direct proto file.

### ISSUE THREAD

**Issue by chaitanya9186** [pubref/rules_protobuf#94]
Please find more info: https://github.com/pubref/rules_protobuf/issues/86#issuecomment-297517125

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
