### ISSUE TITLE
Internal Imports doesn't work when the imported proto depends on external

### ISSUE THREAD

**Issue by junghoahnsc** [pubref/rules_protobuf#98]
Hello,

I have two protos like
`A/a.proto`
`B/b.proto`

and `A/a.proto` imports `google/protobuf/descriptor.proto`

When I used
```
go_proto_library(
    name = "test_proto_go",
    proto_deps = [
        "//A:a_proto_go",
    ],
    protos = ["b.proto"],
)
```
it failed due to `google/protobuf/descriptor.proto` import failure.

When I used `deps` instead of `proto_deps`, I got `A/a.proto: File not found.` error.

Is there something wrong with my usage?

Thanks,

**Comment by pcj** [comment]
Hi @junghoahnsc which rules_protobuf version/commit are you using?

**Comment by pcj** [comment]
Looks like the importmapping is not being correctly assigned.  As a workaround, you should be able provide the mapping explicitly:

```

go_proto_library(
    name = "b_proto_go",
    protos = ["b.proto"],
    proto_deps = [
        "//a:a_proto_go",
    ],
    imports = [
        "external/com_github_google_protobuf/src",
    ],
    inputs = [
        "@com_github_google_protobuf//:well_known_protos",
    ],
    deps = [
        "@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library",
    ],
    importmap = {
        "google/protobuf/descriptor.proto": "github.com/golang/protobuf/protoc-gen-go/descriptor",
    },
    verbose = 3,
)
```

**Comment by junghoahnsc** [comment]
Thanks for looking into this. Once this issue is fixed, can I just specify proto_deps or should I still give other options like imports, inputs, deps?

Unfortunately the workaround doesn't seem to be feasible in out case due to many transitive dependencies.

**Comment by pcj** [comment]
Couple of scenarios:

1. Design default rules_protobuf such that it *always* includes `:well_known_protos`, requiring no additional configuration to use things like `descriptor.proto`.  I have a PR up to accomplish this but still a bit rough. 
 Convenient, but may be surprising.  
2. Automatically add in necessary deps, imports if there exists a dependency on `:well_known_protos`, similar to rules_go.
3. Require explicit configuration, like it is now.

**Comment by junghoahnsc** [comment]
I think (2) would be the best option.

**Comment by junghoahnsc** [comment]
@pcj I'm trying to find a workaround for now. Even if I have a copy of well-know protos in my local repo, it seems like I have to set all attributes like imports. Is that right?

**Comment by junghoahnsc** [comment]
@pcj do you have any plan for this?
Currently I'm using a simple wrapper rule to add well_known_protos always.

BTW, for python, I added a `py_library` by using `native.py_library` as other xx_proto_library does.
It seems to work, but I'm not sure whether it works generally.

**Comment by pcj** [comment]
@junghoahnsc I agree with (2) probably being best option.  Have not had time to address it fully yet, sorry for delay.

As for (2), interesting, would be interested in seeing your impl.  At some point when native proto rules catch up with various scenarios, will likely need to a major rewrite to use the native ones as much as possible and eliminate duplicate rules.

**Comment by junghoahnsc** [comment]
> As for (2), interesting, would be interested in seeing your impl. ....

If you mean `py_proto_library` hack, I just did like

```
 load("@org_pubref_rules_protobuf//python:rules.bzl", _py_proto_compile = "py_proto_compile")
  ...
    _py_proto_compile(
        name=name + ".pb",
        protos=srcs,
        imports=[
            "external/com_github_google_protobuf/src",
        ],
        inputs=[
            "@com_github_google_protobuf//:well_known_protos",
        ],
        deps=[dep + ".pb" for dep in deps],
        with_grpc=has_services)

    native.py_library(name=name, srcs=[name + ".pb"], deps=deps)
```

**Comment by junghoahnsc** [comment]
And also, when a proto imports other proto from other repo (through new_local_repository), go import isn't set correctly.

For example, when a proto imports proto 'A' in the same repo,
the generated go code is like

```
import _ ".../a_proto_go"
```

But when a proto is imported from other repo, the code is like

```
import b "external/b"
```

So, I have to set import_map explicitly.

Is this expected? Or is it a bug?

**Comment by junghoahnsc** [comment]
Is there a way to find and all imports of transitive dependencies with a bazel macro?
I could add a static import (like wkp), but couldn't find a way to add custom dependent imports.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
